### ISSUE TITLE
moment-timezone break down the js file by timezone to reduce file size?

### ISSUE THREAD

**Issue by web-programmer-here** [moment/moment-timezone#1007]
### Moment-timezone version which you use:

Version: 0.5.37

### Issue description:

I am facing this issue where my output js file is huge because of moment-timezone. Is it possible to export individual js file for timezones so not all timezones are exported? 

something like 
```
Asia-tokyo.js
Australia.js
```

so I can manually import these?

**Comment by gilmoreorless** [comment]
I answered your related question at https://github.com/gilmoreorless/moment-timezone-data-webpack-plugin/issues/53 before I saw this issue, but I'll answer again here for posterity.

Given Moment Timezone's current maintenance-only status, it's very unlikely that there'll be any changes to the output format. Partly because other file output changes in the past have sometimes caused more complaints than they've solved (Moment Timezone is consumed in many, many different ways).

I suggest writing your own script to iterate through the zones you want, using [`moment.tz.filterLinkPack()`](https://momentjs.com/timezone/docs/#/data-utilities/filter-link-pack/) to filter the total dataset down to what you need. It'll be easiest to work with the **un**packed file (`data/unpacked/latest.json`) as the data source, as that's already in a format that will work with `filterLinkPack()`.
