### ISSUE TITLE
Why is europe/berlin everywhere?

### ISSUE THREAD

**Issue by cexyboy** [moment/moment-timezone#1029]
### Moment-timezone version which you use:

Version: Latest

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:

Is there a reason why `Europe/Berlin` is also included in zones for these countries:
```
"DK",
"NO",
"SJ",
"SE"
```
If so, why? what's the reason?

**Comment by gilmoreorless** [comment]
Short answer: That's how the [IANA tzdb source defines it](https://github.com/eggert/tz/blob/44499c6fcc8e47c3a3b355328eb9e2acf2c3092c/zone1970.tab#L134), since version [2021b](https://mm.icann.org/pipermail/tz-announce/2021-September/000066.html).

Long answer: This was one of the more controversial decisions in tzdb's history (to the point where [the project got forked for Java's tzupdater software](https://mm.icann.org/pipermail/tz/2021-September/030400.html)). There used to be a convention that there would be at least one primary zone per country (as defined by ISO 3166 codes). But that was only a convention and not actually a documented policy of the project.

In the last few years there have been clean-ups to merge zones that have been identical since 1970, _even if they represent different countries_. Without digging too much into the arguments for or against, this is the end result:
* The countries Germany, Denmark, Norway, and Sweden have had identical time zone rules since 1970. Therefore they're all represented by the single primary zone record `Europe/Berlin`.
* The previous zones `Europe/Copenhagen`, `Europe/Oslo` and `Europe/Stockholm` are now [alias links pointing to `Europe/Berlin`](https://github.com/eggert/tz/blob/44499c6fcc8e47c3a3b355328eb9e2acf2c3092c/backward#L223-L236)).
