### ISSUE TITLE
When will the moment time zone release a new releaseof Egyptian Daylight Time

### ISSUE THREAD

**Issue by xizhilanting** [moment/moment-timezone#1043]
Hello, I have been using Moment Time Zone to process daylight saving time recently. I would like to ask when a new version of Moment Time Zone can be released for Egyptian daylight saving time

**Comment by gilmoreorless** [comment]
The process is:

1. The Egyptian government needs to actually finalise their proposed change into a proper law. Nothing else will happen until after this, because they have a history of cancelling proposals: https://codeofmatt.com/time-zone-chaos-inevitable-in-egypt/
2. After that, the IANA time zone database will release a new version containing the rule changes.
3. Only then can Moment Timezone update the rules and release a new version.

**Comment by xizhilanting** [comment]
Is there a plan to resolve the summer time issue in Morocco and Palestine, or are they based on the same principles as in Egypt

**Comment by gilmoreorless** [comment]
Pretty much the same scenario. As far as I know, the IANA coordinators are waiting for a final confirmation on the correct official dates for Palestine.
Once there's a new tzdb release out, I'll try to get a new `moment-timezone` version published quickly.

(The _real_ solution here is for governments to not announce time changes on such short notice. But that's a much harder fix. 😉)

**Comment by xizhilanting** [comment]
Excuse me again, is there any news about the changes in Morocco? Is the moment-timezone also waiting for official news

**Comment by gilmoreorless** [comment]
Yes, this project can't do anything until there is a new tzdb release containing the changed dates, for all those countries.

**Comment by xizhilanting** [comment]
Thank you for your reply.

**Comment by aelbawab** [comment]
Any update on this as 

Iana has releaed new database 2023 a
Applying DST to egypt

https://data.iana.org/time-zones/tzdb/NEWS

**Comment by gilmoreorless** [comment]
[These changes](https://github.com/moment/moment-timezone/pull/1047) have been released in Moment Timezone `0.5.42`
