### ISSUE TITLE
new iana release announcement for version 2023b

### ISSUE THREAD

**Issue by Om4ar** [moment/moment-timezone#1048]
hello 👋 

iana just announced the release of 2023b [here](https://mm.icann.org/pipermail/tz-announce/2023-March/000078.html )

and it is now available to be integrated

**Comment by gilmoreorless** [comment]
Yes, they did, that is a correct statement of fact. But what is your point? Do you want this project to update? In that case, actually say so.

I can see you've copy-pasted the same message to several datetime-related projects, which frankly shows a lack of respect for the maintainers. Because if you _did_ have respect for the maintainers, you'd have done a quick check for the state of the latest release, and modify the message for each project. And at that point you'd realise that Moment Timezone [has already done a release that integrates this version](https://github.com/moment/moment-timezone/releases/tag/0.5.42).

**Comment by Om4ar** [comment]
@gilmoreorless sorry about this will take care next time
