### ISSUE TITLE
"Friendly" should be invalid date, but it read as valid date

### ISSUE THREAD

**Issue by elliotching** [moment/moment-timezone#1071]
### Environment

For bug reports, please run the following code in your environment and include the output:

```js
console.log({
  moment: moment.version,
  momentTz: moment.tz.version,
  date: (new Date()).toString(),
  intlZone: new Intl.DateTimeFormat().resolvedOptions().timeZone,
});
```

### Issue description

A word "Friendly" is being false positively recognised as valid date, which should not be the case.

```
console.log({
    moment: moment.version,
    momentTz: moment.tz.version,
    date: (new Date()).toString(),
    intlZone: new Intl.DateTimeFormat().resolvedOptions().timeZone,
  });
console.log(moment("Friendly", "ddd, MMM DD, YYYY").toString())
```

```
{
  moment: '2.29.4',
  momentTz: '0.5.43',
  date: 'Wed Jul 26 2023 14:37:50 GMT+0800 (Malaysia Time)',
  intlZone: 'Asia/Kuala_Lumpur'
}
Fri Jul 28 2023 00:00:00 GMT+0800
```

### Expected Output

```
{
  moment: '2.29.4',
  momentTz: '0.5.43',
  date: 'Wed Jul 26 2023 14:37:50 GMT+0800 (Malaysia Time)',
  intlZone: 'Asia/Kuala_Lumpur'
}
"Invalid date"
```

**Comment by sslincoco** [comment]
您的邮件已收到,我会尽快给您回复。

**Comment by gilmoreorless** [comment]
The `ddd` at the start of the format string is looking for a day name. Since day names can be any string based on locale, I _suspect_ it's treating "Friendly" as the name, then moving on to look for the other parts of the date. It doesn't find any and uses lenient fallbacks.

Trying to parse it without the format string, or with different format strings, produces the expected result:

```js
moment("Friendly").toString();  // 'Invalid Date'
moment("Friendly", "YYYY").toString();  // 'Invalid Date'
moment("Friendly", "MMM DD, YYYY").toString();  // 'Invalid Date'
```
