### ISSUE TITLE
The moment-timezone get the time zone of Kazakhstan Asia/Almaty in January 2024 to the DST.

### ISSUE THREAD

**Issue by nomoreyou** [moment/moment-timezone#1102]
### Environment

hi @gilmoreorless i got a problem with moment-timezone and jdk. The performance of moment-timezone and JDK in processing Asia/Almaty time zones is different. Moment-timezone considers that January in Kazakhstan is in DST, and isDST is true, while JDK is false.
 please help me
```js
const moment = require('moment-timezone');

const m = moment.tz('2024-01-01 08:22:33','Asia/Almaty');
const is = m.isDST();

console.log('is----------',is); //true;
```

but jdk consider it's time is not DST time 
![image](https://github.com/moment/moment-timezone/assets/17588322/2007ee63-8858-47e1-8b84-7d34d0aab2c3)

**Comment by gilmoreorless** [comment]
Moment's `isDST` method has a [warning in the documentation](https://momentjs.com/docs/#/query/is-daylight-saving-time/):

> **NOTE:** This function is a HACK. moment has no way of knowing if a given time is in actual DST or not. Some time changes in a zone are DST related, some are not, and without complete timezone information it can't know.
>
> Moment currently checks the winter and summer time, and if the offset matches the summer offset (and summer off is different than winter off), then it reports DST. This works in vast majority of cases, but as mentioned above, is not "correct" and won't work for all cases.

Because eastern Kazakhstan had a one-off change of time zone, the naive guessing in Moment is being tripped up and thinks it's a DST shift. Although it's unfortunate, it's not something we're likely to fix, given the maintenance-only status of the project.

**Comment by sslincoco** [comment]
您的邮件已收到,我会尽快给您回复。

**Comment by gilmoreorless** [comment]
@sslincoco Please disable your email auto-responder for open source projects.
