### ISSUE TITLE
Module not found: TypeCannot read properties of undefined (reading 'startsWith') 

### ISSUE THREAD

**Issue by bigbizze** [moment/moment-timezone#1122]
```
./node_modules/moment/moment.js
Module not found: TypeCannot read properties of undefined (reading 'startsWith')

Import trace for requested module:
./node_modules/moment/moment.js
./node_modules/moment-timezone/moment-timezone.js
./node_modules/moment-timezone/index.js
./node_modules/date-holidays-parser/src/Equinox.js
./node_modules/date-holidays-parser/src/CalEventFactory.js
./node_modules/date-holidays-parser/src/DateFn.js
./node_modules/date-holidays-parser/src/Holidays.js
./node_modules/date-holidays-parser/src/index.js
./node_modules/date-holidays/src/Holidays.js
./node_modules/date-holidays/src/index.js
```

I am not sure what is causing this issue, I'm assuming it's some dependency thing between `date-holidays`, `date-holidays-parser`, `moment-timezone` and `moment`. 

----

I have my resolutions set to:

```json
  "resolutions": {
    "date-holidays-parser": "^3.4.4",
    "moment": "^2.29.4",
    "moment-timezone": "0.5.43"
  },
```

and i am using `date-holidays@3.23.12`

----

date-holidays issue: https://github.com/commenthol/date-holidays/issues/487
date-holidays-parser issue: https://github.com/commenthol/date-holidays-parser/issues/59
moment issue: https://github.com/moment/moment/issues/6259

**Comment by gilmoreorless** [comment]
> I am not sure what is causing this issue, I'm assuming it's some dependency thing between `date-holidays`, `date-holidays-parser`, `moment-timezone` and `moment`.

If you can't narrow down the area of the problem, there's nothing that any of those libraries' maintainers can do. Each library is working fine in normal circumstances (which we know because there'd be a lot of raised issues otherwise). Given the lack of line numbers in the error trace, it looks to me like a third-party module loading system has thrown the error, which is not possible for us to diagnose.

In addition, creating the same identical issue in 4 repos comes across as quite disrespectful of other people's time.
