### ISSUE TITLE
Moment objects have a confusing api - exposes spurious dates as _d

### ISSUE THREAD

**Issue by JonnyRa** [moment/moment-timezone#139]
Im paraphrasing a bit here but my code is something like this:

```
        approxRegistrationTime = Date.now();
        ....
        //some retrieval from server + parsing

        var something = moment.tz(approxRegistrationTime, "UTC");
        var somethingElse = moment.tz({year: year, month: month-1, day: day, hour: hour, minute: minute}, "Europe/Stockholm");
```

with values for the same time in utc and stockholm time these show the following as _d

something - Fri Oct 17 2014 11:59:43 GMT+0100 (GMT Daylight Time)
somethingElse - Fri Oct 17 2014 13:59:00 GMT+0100 (GMT Daylight Time)

However getting the date using toDate() on both items returns the expected values (albeit in local time)

This is confusing - the documentation doesnt tell you what type anything returns or what you can do with them so I went for looking at it in the debugger.  I'm guessing _d is a private field but at first glance its the only thing with a date on there.

Also (as a bit of an aside) you stuck with the zero indexed months.  What's that all about?!

Cheers for the library though, despite the quirks it seems to do what it says on the tin.

**Comment by guntram** [comment]
+1 @JonnyRa !
The _d is public as I can access it.
The _d contains just the date I need, all "public" functions like format(), toDate(), toISOString(), ... do something unpredictable.
Then I am told everywhere that I MUST NOT use the _d object and my brain goes like: ????!?!!!????

Momentjs seemed so great until I noticed that I cannot use the _d object....

**Comment by maggiepint** [comment]
@guntram if you are using moment timezone then accessing _d simply will not work. It will always give you wrong values. I honestly have no idea why you are using moment at all if you just want to use javascript date. Seems like needless overhead.
If you have questions about how functions work, happy to answer them in gitter.

**Comment by guntram** [comment]
I need to create dates including a different timezone than the clients os
is running. I use the _d because it contains the timezone I set when
creating the object. When i switch my client machines timezone the dates in
the _d seem to be correctly created, always the same - ignoring the os
timezone.
So I have to figure out how to do this without rhe _d but it doesn't work
consistently...

And thanks for the superfast answer (on such an old thread)!!

Am 21.07.2016 16:04 schrieb "Maggie Pint" <notifications@github.com>:

@guntram <https://github.com/guntram> if you are using moment timezone then
accessing _d simply will not work. It will always give you wrong values. I
honestly have no idea why you are using moment at all if you just want to
use javascript date. Seems like needless overhead.
If you have questions about how functions work, happy to answer them in
gitter.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/moment/moment-timezone/issues/139#issuecomment-234263285>,
or mute the thread

**Comment by guntram** [comment]
I need to create dates from UTC timestamps with the timezone of the country from where the dates were written into the db.
Additionally, I need Date objects because i need them for a chart, which won't work with dates formatted into strings.

So here is what seems to work for me (for example with Berlin timezone):
moment.tz(moment('2016-Jun-20 00:00:00', 'YYYY-MMM-DD HH:mm:ss'), 'Europe/Berlin')._d;

One of the examples which doesn't work:
row.date = moment.utc('2016-Jun-20T00:00:00.000', "YYYY-MMM-DD HH:mm:ss").tz('Europe/Berlin').toDate();
I tried a lot of combinations including toISOString() or format()...

**Comment by guntram** [comment]
Maybe this clears things up (while having my local OS timezone set to Hawaii):

moment.tz(moment("2016-Jun-22 00:00:00", "YYYY-MMM-DD HH:mm:ss"), "Europe/Berlin").format();
=> "2016-06-22T12:00:00+02:00"

moment.tz(moment("2016-Jun-22 00:00:00", "YYYY-MMM-DD HH:mm:ss"), "Europe/Berlin").toDate();
=> Wed Jun 22 2016 00:00:00 GMT-1000 (Local Standard Time)

moment.tz(moment("2016-Jun-22 00:00:00", "YYYY-MMM-DD HH:mm:ss"), "Europe/Berlin")._d;
=> Wed Jun 22 2016 02:00:00 GMT-1000 (Local Standard Time)

I need the result of the third one, as it is correct and the first two are wrong...
The date and time in the third are correct, the GMT-1000 is not correct, but I wouldn't care as I only need the correct Date "Wed Jun 2016 02:00:00" in the object.

**Comment by guntram** [comment]
...btw i never used gitter, don't know how to do this... :)

**Comment by maggiepint** [comment]
So basically you want to convert a date you know to be in Berlin time to the time of your local machine?

```js
moment.tz("2016-Jun-22 00:00:00", "YYYY-MMM-DD HH:mm:ss", 'Europe/Berlin').local().format()
"2016-06-21T15:00:00-07:00"
```

Note that I am on Pacific time, so I get -7. 

I think this blog post will help you:
https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

**Comment by guntram** [comment]
Thanks for the blogpost, I read it but I am not sure yet how it could help me. I am gonna go through this again tomorrow, it is hot and work loaded my brain too much ;) .

What you just wrote does not give the correct date, does it?
```
moment.tz("2016-Jun-22 00:00:00", "YYYY-MMM-DD HH:mm:ss", 'Europe/Berlin').local().format()
"2016-06-21T15:00:00-07:00"
```
Shouldn't the result be something like:
```2016-06-22 02:00:00```
because that is the correct date and time for a UTC date ```2016-Jun-22 00:00:00``` with the offset ```+0200```, or maybe i do not understand all this date and time stuff...

And, I suppose your _d contains that value, right? ;)

**Comment by maggiepint** [comment]
A UTC date cannot have an offset of +2. A utc date always has an offset of 0.

What that code does is say 'take this date, and interpret it as Berlin time. Then change it from Berlin time to my local time.'

I think maybe you are asking me for 'interpret this date as UTC, and then convert it to Berlin time'. That would be:

```js
moment.utc("2016-Jun-22 00:00:00", "YYYY-MMM-DD HH:mm:ss").tz('Europe/Berlin').format()
"2016-06-22T02:00:00+02:00"
```

**Comment by guntram** [comment]
That sounds good. I am checking this out tomorrow and post the result.
Thanks alot!

Am 21.07.2016 18:59 schrieb "Maggie Pint" <notifications@github.com>:

**Comment by guntram** [comment]
So, the date is correct, but it is a string.
And toDate() converts the date to the local zone:
```moment.utc("2016-Jun-22 00:00:00", "YYYY-MMM-DD HH:mm:ss").tz('Europe/Berlin').toDate()
Tue Jun 21 2016 14:00:00 GMT-1000 (Local Standard Time)```
Is ist possible to get the date as a date type with the value format() returns?

**Comment by maggiepint** [comment]
It actually isn't. This is a fundamental limitation of the date object in javascript. It can only understand UTC, and the time of the local machine.

**Comment by guntram** [comment]
As a last comment i want to show what i just watched :dancer: 
Timezones in code:
https://www.youtube.com/watch?v=-5wpm-gesOY

**Comment by mj1856** [comment]
@guntram - Yes.  That is a good one. :)
