### ISSUE TITLE
Issues trying to run moment-with-locales.js and moment-timezone together

### ISSUE THREAD

**Issue by crushred** [moment/moment-timezone#143]
For a framework I'm working on I tried packaging moment-with-locales.js and moment-timezone.js together. All the locale stuff works fine but when i try to use the tz function to set the timezone I get and error that tz does not exist.
This also occurs when I just load the scripts separately.
If I run straight up moment.js and timezones tz works. 
Is there any reason why I can't run the locales with timezone? I have timezone 0.2.2 and moment 2.8.3

**Comment by steakknife** [comment]
This needs a documented example.

**Comment by maggiepint** [comment]
If this is undocumented, happy to take a pull.

**Comment by steakknife** [comment]
This needs a workable solution. I'm not a frontend developer and have NFI how to get this working with babel and brunch, so crowdsourcing would be waiting for Godot.

**Comment by maggiepint** [comment]
@steakknife at the end of the day these are both UMD modules. The JS ecosystem currently has approximately 700 billion ways to use UMD modules. As a team, we aren't able to do anything but crowd source - I can tell you how to use it with grunt, and with webpack, but that's it because that's all I personally use.

**Comment by steakknife** [comment]
We've found a solution. Thanks a brunch!

**Comment by apogupta** [comment]
@steakknife . can you please help to share the solution. we are facing same issue.

**Comment by alexiusp** [comment]
we are having an issue that is probably like this.

I need to use timezones and localized formatting in the same .js file. Right now I need to do like this:
```
import tzmoment from 'moment-timezone';
import moment from 'moment';
```
and then use tzmoment and moment as standalone packages: tzmoment to parse timezones and moment to format dates to localized output.

Is it possible to "merge" imports somehow, so that I would need to import only moment-timezone and use localized formatting?

**Comment by olastor** [comment]
+1

**Comment by gilmoreorless** [comment]
Given the age of this issue, and the high rate of change of dependency managers in the JS ecosystem, this is near impossible to diagnose. If this problem is still happening, it's best to create a new issue with more details.
