### ISSUE TITLE
moment-timezone returns insane values (when you misuse it)

### ISSUE THREAD

**Issue by jwalton** [moment/moment-timezone#150]
```
var moment = require('moment-timezone');
console.log(moment("2014-11-08 12:29:00", "America/Montreal").valueOf()
console.log(moment("2014-11-08 12:29:00", "America/Montreal").toString()
```

Prints:

```
-61232701200000
Sun Aug 12 0029 00:20:00 GMT-0400
```

...

Oh, I just realized I should be calling `moment.tz(...)`.  But, ummm... this is exciting.  Not sure if there's a good way to test for someone doing something stupid like this.  :P

**Comment by mj1856** [comment]
The moment constructor function would need additional logic to interpret whether the supplied string looked like a time zone instead of a valid formatting string.  Or it would just need to validate if it was a valid formatting string.  I don't think that's necessarily a good idea, as it would at bloat to the function.  Also, sometimes you *do* need to intersperse extraneous characters in the formatting string.  I don't know how we could reasonable distinguish a valid use from an invalid use.
