### ISSUE TITLE
Timezones can be parsed lazily

### ISSUE THREAD

**Issue by justinsb** [moment/moment-timezone#155]
I noticed that when one timezone is requested, all are parsed.  Unpacking the timezone is a (relatively) heavy operation.

Would it be OK if I provided a patch that parsed the timezone data lazily?  I'm thinking either I could change the input data format so that it is a map from string to the packed data, or I could just do the splitting out of the name at first, and defer the full unpacking till the timezone was actually used.

**Comment by mj1856** [comment]
:+1:

**Comment by davidpean** [comment]
@justinsb @kashifshamaz21 @timrwood was just about to create a similar issue :). We are using moment and moment timezone on the new ESPN.com in order to show localized game dates for users. @paulirish recent did a perf audit, and mentioned that moment was taking ~400ms up front. I looked into it, and it was the initializing of moment-timezone -- specifically the unpacking of every timezone. On Chrome Android with a Nexus 4, I am actually seeing ~500ms. Has anyone had any luck playing around with only unpacking the timezone that is requested?

![screenshot 2015-05-06 12 28 04](https://cloud.githubusercontent.com/assets/317856/7498091/59b91a16-f3ec-11e4-880e-d053cb6da571.png)

**Comment by kashifshamaz21** [comment]
@davidpean Unfortunately, been caught with other stuff, haven't been able to contribute much for the team for sometime. So, no updates from my end on this!

**Comment by davidpean** [comment]
@kashifshamaz21 @timrwood @justinsb - I took a stab at making a small change that will only execute the unpack for the one timezone if it hasn't been done already. https://github.com/davidpean/moment-timezone/commit/b892d54e8925ac3fef765a027bd79b09caad1f61- On initial load desktop is around ~2ms, and Chrome Android ~30 now. I'm not too familiar with the library so please let me know what you think!

**Comment by paulirish** [comment]
Pull request up at https://github.com/moment/moment-timezone/pull/211

Pretty massive win. Nice one.

**Comment by mj1856** [comment]
Very nice, and glad to hear about the ESPN usage!  :smile:
