### ISSUE TITLE
DST not working for GMT time zone

### ISSUE THREAD

**Issue by rwilliams-scottlogic** [moment/moment-timezone#221]
Times in DST return isDST true for CET and WET, but not for GMT.

This seems like it would be a big problem for many people, so I may be missing something or it's by design from moment-tz or IANA because GMT is special in some way.

See console output from http://jsfiddle.net/32x87L2x/1/

```
console.log(moment.tz("2015-01-01", "CET").isDST());
console.log(moment.tz("2015-08-01", "CET").isDST());

console.log(moment.tz("2015-01-01", "WET").isDST());
console.log(moment.tz("2015-08-01", "WET").isDST());

console.log(moment.tz("2015-01-01", "GMT").isDST());
console.log(moment.tz("2015-08-01", "GMT").isDST());
```

```
false
true

false
true

false
false <<< shouldn't this be true?
```

Using "Europe/London" gives what I'd expect to be the correct result - August is in DST.

**Comment by mj1856** [comment]
This is by design of GMT itself.  GMT never changes.  It is fixed at `+00:00`.  Great Britain, represented by `Europe/London`, uses GMT as its standard time, and BST (British Summer Time, `+01:00`) as its daylight time.

`GMT` is modeled correctly in the IANA sources, and moment uses it as-is.

BST is not modeled at all, because it is an ambiguous abbreviation - it might also stand for Bangladesh Standard Time, or some other time zone.  In general, many time zone abbreviations are  ambiguous, and can't be used independently.  Zones like `CET` and `WET` are only in the time zone database because they were part of the POSIX standard, and are needed for backwards compatibility purposes.

**Comment by rwilliams-scottlogic** [comment]
Thank you.
