### ISSUE TITLE
What's the difference between zone.parse and zone.offset

### ISSUE THREAD

**Issue by zhangchiqing** [moment/moment-timezone#246]
According to [the document](http://momentjs.com/timezone/docs/#/zone-object/offset/), both `zone.parse` and `zone.offset` accept a timestamp and return the offset. Why `zone.parse` and `zone.offset` print different offset result? What's the difference between them?
```
var zone = moment.tz.zone('America/New_York')
zone.parse(Date.UTC(2015, 10, 1, 4, 30, 0)); // => 300
zone.offset(Date.UTC(2015, 10, 1, 4, 30, 0)); // => 240
```

**Comment by mj1856** [comment]
I agree the documentation isn't very clear.  The difference is that `zone.offset` takes a true UTC-based timestamp, while `zone.parse` takes an timestamp that is based on that particular time zone.

In other words, even though `Date.UTC` returns the number of milliseconds since `1970-01-01T00:00:00Z`, the `zone.parse` function treats it as if it were the number of milliseconds since either `1970-01-01T00:00:00-05:00` or `1970-01-01T00:00:00-04:00` (for the `America/New_York` zone), depending on which is in effect for the given timestamp.  If the time could exist in both offsets (or can't exist in either), then the rules detailed in [Parsing Ambiguities](http://momentjs.com/timezone/docs/#/using-timezones/parsing-ambiguous-inputs/) are followed.

**Comment by mj1856** [comment]
IMHO, `zone.parse` doesn't have many external use cases.  I would have expected it to be an internal function, not exposed through the public API.

**Comment by mj1856** [comment]
Also, note that the ambiguous parsing behavior has changed with #101 - and the docs have not yet been updated.

**Comment by zhangchiqing** [comment]
Cool! Thanks @mj1856  for the explanation :)
