### ISSUE TITLE
toJSON handled incorrectly by moment.tz

### ISSUE THREAD

**Issue by elwayman02** [moment/moment-timezone#250]
If I create a regular `moment()` by passing in ISO format with a time (relative to midnight UTC) and timezone, moment parses the date and `toJSON` correctly. However, if you pass the same date to `moment.tz()`, the underlying date object is again the same but `toJSON` returns a different output. See screenshot below for more details:

![developer_tools_-_https___secure-jordan_checkmate_io_hotel_dashboard_conversations_arrivals](https://cloud.githubusercontent.com/assets/1325482/10061335/ac610254-620c-11e5-91cf-d448495ce0e5.png)

moment: ~2.10.6
moment-timezone: 0.3.1

**Comment by timrwood** [comment]
This is behaving correctly.

The first call includes an offset of `+08:00`, so it is being parsed with that offset.

At 8:00 am in `+08:00` it is 12am in `+00:00`.

The second call is at 12am in Perth, which has an offset of `+08:00`.

At 12am in `+08:00`, it is 4pm in `+00:00`.

The underlying date object we use is a private variable, and does not always match the unix epoch that the moment represents. Because the `Date` api does not provide getters and setters for arbitrary offsets, we add or subtract the offset from the underlying date equivalent to the minutes in `mom._offset`.

For the first call, you probably want one of the following.

```js
moment('2015-09-25T00:00:00+08:00') // 12 am AWST
moment('2015-09-25T08:00:00+00:00') // 8 am GMT
```
