### ISSUE TITLE
America/New_York timezone formats date in EDT instead of EST

### ISSUE THREAD

**Issue by ngyangjo** [moment/moment-timezone#307]
I'm using following code to format time in string as per the provided timezone.

`moment.tz(1457063929894, "America/New_York").format("YYYY-MM-DD HH:MM:ss z")`

The response returned is 

2016-03-03 23:03:49 EDT instead of 2016-03-03 22:58:49 EST. Why? The current timezone in New York is EST and it won't be EDT until March 14. Is there something else i've to specify to make it display in EST or is it a bug?

**Comment by mj1856** [comment]
Well, I see you're using `MM` in the minutes position instead of `mm`, so definitely fix that.  But even then, I can't reproduce your result.  I get EST back, not EDT.

How are you loading the data?  From one of the prebuilt files, or manually?  Perhaps if you could reproduce the problem in a jsFiddle, that would help.

Thanks.

**Comment by ngyangjo** [comment]
Thanks for you reply. Turns out i have to update the timezone-data in timezone.js. I updated mine with 2010-2020 data from http://momentjs.com/timezone/ and its working now. Is there any other solution?

**Comment by mj1856** [comment]
That is the correct solution.  Though if you only need data for this one zone, you can take the zone line from there just load it by itself instead of pulling the whole file in.

```javascript
moment.tz.add('America/New_York|EST EDT|50 40|01010101010101010101010|1BQT0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0|21e6');
```
