### ISSUE TITLE
toDate() creating incorrect Date object

### ISSUE THREAD

**Issue by sdesmond** [moment/moment-timezone#309]
`moment.tz(1493092800000, 'America/New_York');`

produces a Moment of "Tue Apr 25 2017 00:00:00 GMT-0400"

but `moment.tz(1493092800000, 'America/New_York').toDate()`

produces a Date of "Mon Apr 24 2017 22:00:00 GMT-0600 (Mountain Daylight Time)" 

I am in Mountain Time, but I would expect `toDate()` to construct a date object that matches the current moment, not a timezone adjusted one.

**Comment by mj1856** [comment]
The `Date` object has no time zone abilities other than working with the local time zone.  We can't do anything about that.  When you use `toDate`, any of moment or moment-timezone's ability to "represent" other time zones is stripped away.  You're left with the raw instant in time represented by the timestamp, and then the `Date` object converts that to local time when displaying it as a string.

You might as well have just done `moment(1493092800000).toDate()` or `moment.utc(1493092800000).toDate()`.  It's all the same as just `new Date(1493092800000)`.

To benefit from moment-timezone, you have to use moment's native functions, such as `format`.

**Comment by sdesmond** [comment]
Consider this detail from my above post.  I have a date that was saved in Eastern time, but I'm not necessarily in Eastern time.  I need to use the date as parsed in Eastern.  I need to work with this date throughout my application, and I can as long as I keep it a moment.  What do I do when I need to convert this to a Date then?  I currently have this long-winded solution.

`new Date(moment.year(), moment.month(), moment.date(), moment.hours(), moment.minutes(), moment.seconds(), moment.milliseconds())`

What's the alternative?

**Comment by mj1856** [comment]
Sorry for the delayed response...

The approach in your last comment is not good.  The `Date` object it creates no longer reflects the correct point in time.   It will be shifted by the difference between the local time zone and the one being used in moment.

You said you have a date saved in Eastern time, and that you're parsing it in Eastern.  But your example doesn't show that.  Your example shows a numeric timestamp, `1493092800000`, which will always be interpreted as UTC.  By using the `tz` function with `America/New_York`, you're converting that value from UTC to Eastern for *display* purposes - such as when calling `.year()`, `.month()`, `.date()`, `.format()`, etc.  Internally though, it's still the same number.

Also, you haven't said *why* you need a `Date` object.   In many cases, you can do without it.

You seem to think that somehow moment could give you back a `Date` object that is in Eastern time.  It can't do that.  Nobody can, because that's not how the `Date` object works.  The `Date` object is simply tracking UTC, and converts it to local time for display.  That's it.

**Comment by sdesmond** [comment]
You may be right that if I converted to moment throughout my application,
this wouldn't really be an issue.  I'm using Angular which has a built-in
filter for displaying Date objects.  I suppose I just need to write a quick
little filter for moment objects and I'd be fine.  I'm converting to Date
because that's what I'm using in most of the application, and I just
introduced moment for some particularly tricky date manipulation.

In the beginning I was trying to display the date an action was taken which
was recorded as something like Jan 1, 2000 00:00:0000.  When I parsed the
date and displayed it, I was getting Dec 31, 1999 so all my dates were off
by a day.  I had assumed that `dateObject.hours()` and
`momentObject.toDate().getHours()` would return the same value so I was
thrown off when they didn't.  I guess I may just have to bite the bullet
and convert everything to moments.  Thanks for the responses.

**Comment by mj1856** [comment]
Mutating the object will indeed change the timestamp.  When you call `hours(12)`, you're setting it to the 12:00 noon hour in whatever the current mode of the moment object is.  Since it's currently set for the `America/New_York` time zone, then you're setting it to noon Eastern time.  The timestamp will be adjusted to the equivalent UTC point in time, which would be `1493136000000`, or `2017-04-25T16:00:00Z`.

If your own computer is in the Mountain time zones, then that same timestamp would be `2017-04-25T10:00:00-06:00`, so a `Date` object would show that as the equivalent local time.

**Comment by mj1856** [comment]
If you're going to be using moment with angular, then my recommendation would be to use the [angular-moment](https://github.com/urish/angular-moment) library, which provides angular filters for moment objects without converting them to `Date` objects.

I'm not sure how to advise you with regard to the rest, other than to say that saving to a database usually involves serializing to some string format or timestamp - both of which you can get from moment directly without converting to a `Date` first.

I'll also say that usually I see folks converting to `Date` to pass to a date-picker UI control of some time.  Many of those controls will indeed give you a `Date` object, but they also (usually) have a different property to work with the value as a raw string, either in the provided input format, or in ISO format.  Use those methods when available.

Hope that helps.

**Comment by sdesmond** [comment]
Alright.  I had assumed that the .tz() method would mutate the object.  From what you've already said, it's just for display purposes.  I might argue that it should mutate the object, but I'm sure you've thought this through more than I have.  I'll probably just look at converting to moments everywhere and that should solve my issues.  Thanks again.

**Comment by theTrip73** [comment]
I think I'm having a related issue that could use some advice. I'm using moment-timezone with jQuery UI plugins datepicker and datetimepicker. I'm all squared away with getting the timestamp to save in UTC.

When I parse this to local time using the following code that should show me 12:00 PM, it actually gives me 11:00 AM. I think Daylight Savings Time is somehow the problem, since the given date is in CST while the current timezone is CDT, but it looks to me like I'm doing everything correctly.

```
		localTime = moment.tz("2016-03-09 18:00:00", "YYYY-MM-DD HH:mm:ss", "America/Chicago");
		$('#expires_at').datetimepicker('setDate', localTime.toDate());
```

I've verified that ```localTime.toDate()``` returns "12:00 -0600", so it seems like it should be working. My guess is that datetimepicker isn't able to parse the -0600 out of current timezone context which is now -0500 for America/Chicago thanks to DST. Based on what I've read above, this seems like an appropriate conclusion.

Is there a way to handle DST that I haven't figured out, or is this an issue that hasn't been conquered?

Forgive me if this is a duplicate in some way. I searched "DST" in issues and couldn't find anything that matched this.

**Comment by mj1856** [comment]
Not all datepickers are created equally.  You might consider one that's designed with moment in mind.

Here's a few that looks promising that use moment internally.  I've not tried them personally.
http://eonasdan.github.io/bootstrap-datetimepicker/
http://makingsense.github.io/moment-datepicker/
http://ionden.com/a/plugins/ion.calendar/en.html

I'm sure there are others out there.  If you're set on jQuery UI, see if you can get/set the date directly as a string instead of as a `Date` object.

**Comment by windhandel** [comment]
@mj1856, I don't think you're understanding these requests (I've seen a couple of these and I have the same request).

There are two primary use cases for the moment library (if not many more):

- Using moment with a local time scenario.  In this case, you want everything to be displayed in local times because the time zone the application is "running in" is the same as your local time.

- Using moment with a non-local time scenario.  In this case, you want everything to be displayed in non-local times because the user has physically moved outside of the timezone that makes sense to display the data in.  If this business that this information pertains to is in PST and I'm currently located in CST, then I want all data for *the business* to be displayed to all users in the same time zone no matter which time zone they're physically located in.  That way, when I schedule a shipment to arrive, I know it's going to arrive in PST time zone.

Maybe you can accomodate this scenario with another method off of the moment date object other than toDate(), e.g. toTzDate()?

**Comment by windhandel** [comment]
Hi @mj1856,

I'm trying to understand your hard-line stance on "upgrade all date/time components to support moment" given the situation with JavaScript Dates not supporting shifting local time to a timezone of choice.

Why take this stance vs. having moment help adapt times to a timezone of choice.

What **specifically**  is the issue with converting dates to an invalid date/time for the local time zone given the JavaScript issues? i.e. if local time is CST and I want to display everything in PST, why not just output the "wrong" date values to JavaScript since it can't change its local time setting.

Which bugs will arise if you control all of the date I/O with moment?

**Comment by Softman65** [comment]
moment.clone().toDate() works.........

**Comment by McQuinTrix** [comment]
Try : `moment(moment().tz('America/New_York').format("DD/MM/YYYY HH:mm"), "DD/MM/YYYY HH:mm").toDate()`

**Comment by yafetissac** [comment]
Already Fixed At https://icetutor.com/question/moment-js-transform-to-date-object/
