### ISSUE TITLE
Invoking endOf('day') multiple times

### ISSUE THREAD

**Issue by Az4z3l** [moment/moment-timezone#327]
I think I may have found an issue: if I invoke the endOf('day') multiple times I would expect the date to remain the same, but apparently this is not the case during (some) DST transitions:

```JavaScript
moment.tz.setDefault('Europe/Rome');
var date = moment('1979-05-27', 'YYYY-M-D').endOf('day'); 
date.valueOf() // 296693999999
date.endOf('day').valueOf(); // 296776799999
```

Did I get something wrong? In this very case it actually goes to the end of the following day. It does not seem to happen with dates after the 1979.

**Comment by mj1856** [comment]
Well, there's a transition in this time zone on this day at midnight.  `1979-05-27T00:00:00+01:00` => `1979-05-27T01:00:00+02:00`.   [See here also](http://www.timeanddate.com/time/zone/italy/rome?year=1979).

However, there still looks to be a bug. It's more clearly demonstrated this way:

```javascript
var m = moment.tz('1979-05-27', 'YYYY-M-D', 'Europe/Rome');
m.format();  // "1979-05-27T01:00:00+02:00"   (correct)
m.endOf('day');
m.format(); // "1979-05-28T00:59:59+02:00"  (incorrect, should be "1979-05-27T23:59:59+02:00")
```

This appears to be due to the implementation of `endOf` in moment.  To calculate the end of the day, it does the start of the day, plus one day, less one millisecond.  That logic fails when the day doesn't start at midnight.  I'll log this in the moment issue tracker, as it needs to be fixed there.

**Comment by mj1856** [comment]
We'll track in moment/moment#3132.  Thanks for reporting.
