### ISSUE TITLE
CEST not recognized (returned by cordova globalization plugin)

### ISSUE THREAD

**Issue by rienk-git** [moment/moment-timezone#328]
Hi,

I am trying to auto-set timezones in cordova. The globalization plugin returns 'CEST' (Central European Summer Time', which is not recognized as a valid timezone, but is returned by android. It follows [ldml](http://unicode.org/reports/tr35/tr35-4.html ) specs. (setting it to 'CET' does the trick and moment does account for summertime, but I dont know all the summertime abbreviations in the world) Is there a library to convert 'CEST' to 'CET' and all other summertime abbreviations in the world? Or should it be included in moment-timezone?

**Comment by mj1856** [comment]
We use standard IANA time zones.  You can choose from any in the list [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

The reason `CET` works is because it's defined as a zone in the source data.  However, it's primarily there for backwards compatibility reasons.  There are a few other abbreviations still in there, but in general, it is recommended to use the zone identifiers that are in Area/Locality format, such as `Europe/Paris`.

Note that time zone abbreviations can be ambiguous.  They don't necessarily uniquely identify a time zone.  Though they may be used when formatting a display string for a human to read, they are near useless for computers, and thus shouldn't be used as input.
