### ISSUE TITLE
Incorrect time output?

### ISSUE THREAD

**Issue by scheung38** [moment/moment-timezone#344]
import moment from 'moment-timezone';

    > var guessTimeZone = moment.tz.guess()
    undefined

    > guessTimeZone
    'Europe/London'

Current local time 10:57

SUMMER TIME

    > moment.tz('2016-5-20 09:57:00', guessTimeZone).format('YYYY-MM-DD HH:mm:ss')
    '2016-05-20 10:57:00' <- correct output, but incorrect input format

    > moment.tz('2016-05-20 09:57:00', guessTimeZone).format('YYYY-MM-DD HH:mm:ss')
    '2016-05-20 09:57:00' <- incorrect output, correct input format

So my question is how come I needed to remove the leading zero in front of the month data format to get the right answer as I cannot modify external data from provider, unless I parse it within my app?

Or is this a bug within the library?

**Comment by maggiepint** [comment]
I think the issue here is that you have a UTC time, and you want to convert it to local time.

When you use moment timezone the way that you are, you are saying 'take this time and interpret it as local time in the 'Europe/London' time zone.

If you want to say 'Take this UTC time, and convert it to the Europe/London time zone' it would look like this:

```js
moment.utc('2016-05-20 09:57:00').tz( 'Europe/London').format('YYYY-MM-DD HH:mm:ss')
"2016-05-20 10:57:00"
```

As to why you see the 'correct' behavior when you take the zero out - it has something to do with falling back to the JS date constructor. You may have noticed that you also get a deprecation warning. This behavior is unsupported, so even if it happens to provide correct results in this use case, you should instead do what I wrote above.

In addition, I'm not sure why you are bringing in Moment timezone. If you only need to convert a UTC date to the User's local timezone, you can just do this:
```js
moment.utc('2016-05-20 09:57:00').local().format('YYYY-MM-DD HH:mm:ss')
```
Moment timezone is only needed when you need to display a date in a timezone other than the user's local timezone or UTC.

For instance, if you user is in London, but you need to display a date in Los Angeles time to that user, then you would use moment timezone.

**Comment by scheung38** [comment]
Thanks Maggie this simplifies it. Appreciate it.
