### ISSUE TITLE
Timezone conversion bug when a space is present before '+' in source time

### ISSUE THREAD

**Issue by aunko** [moment/moment-timezone#349]
// version info:

//! moment.js
//! version : 2.13.0

//! moment-timezone.js
//! version : 0.5.4

	// apparently, there is a bug in moment:
	// if there is a space before the '+' sign, moment incorrectly converts the time zone 
	var serverTime_bug   = "2016-05-25 23:00:00 +00:00"
	var serverTime_nobug = "2016-05-25 23:00:00+00:00"

	// Incorrect: the following does not convert the date/time to appropriate time zone
	moment(serverTime_bug).tz("America/New_York").format('LLL z');	// shows: May 25, 2016 11:00 PM EDT

	// Correct: 
	moment(serverTime_nobug).tz("America/New_York").format('LLL z');	// shows: May 25, 2016 7:00 PM EDT

**Comment by aunko** [comment]
Apparently, ISO definition does not allow leading spaces before Z, + or - of the time difference. See section 4.2.4 and 4.2.5.2 of ISO document:

http://dotat.at/tmp/ISO_8601-2004_E.pdf

However, moment does allow spaces before Z. I request that moment also allows space before + or -.

Also, SQL Server does return values (DateTimeOffset) with spaces before + or -. It can be easily handled by changing regular expressions in moment.js (added **\s*** before **[+|-]**):

    // iso 8601 regex
    // 0000-00-00 0000-W00 or 0000-W00-0 + T + 00 or 00:00 or 00:00:00 or 00:00:00.000 + +00:00 or +0000 or +00)
    var extendedIsoRegex = /^\s*((?:[+-]\d{6}|\d{4})-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)(\s*[\+\-]\d\d(?::?\d\d)?|\s*Z)?)?/;
    var basicIsoRegex = /^\s*((?:[+-]\d{6}|\d{4})(?:\d\d\d\d|W\d\d\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?:\d\d(?:\d\d(?:[.,]\d+)?)?)?)(\s*[\+\-]\d\d(?::?\d\d)?|\s*Z)?)?/;

**Comment by mj1856** [comment]
This isn't an issue with moment-timezone, but in your use of moment.  Read [these docs](http://momentjs.com/docs/#/parsing/string/) for understanding strings that are supported without specifying a format parameter.

The correct usage when using a non-standard format is to provide a format string.

```javascript
moment("2016-05-25 23:00:00 +00:00", "YYYY-MM-DD HH:mm:ss Z")
```

As pointed out, ISO8601 does not support a space before the time zone offset.  Thus modifying moment to support that would break other things, such as validating that a string is valid ISO8601.

Regarding SQL Server - understand that SQL Server does not return strings at all for types like `datetimeoffset`.  It returns binary custom format over the Tabular Data Stream (TDS) protocol.  It's up to whatever application library your using to read the value from the TDS stream and convert it to the native types in your application code.  it's then up to your application code to produce a string in a particular format.

For example, if you're using .NET, then the SQL Native Client database provider will communicate with SQL Server over TDS.  It translates SQL's binary `datetimeoffset` values to an intermediate format that is then read by ADO.NET and converted to a `System.DateTimeOffset` .NET type.  It's not until you convert to a string representation by calling a method like `.toString()` or going through some other serialization mechanism that the value gets any kind of "format".  So if you're seeing an extra space in your output, it's probably because you're using a culture-specific format in this final step.

For example, calling `DateTimeOffset.Now.ToString()` in .NET while the current culture is `en-US` will give a value such as `"6/5/2016 6:39:37 PM +00:00"`.  Parsing that in moment would *require* a format specifier, because moment has no idea what to do with this data (it could be m/d/y, or d/m/y, etc.).  If instead I call `DateTimeOffset.Now.ToString("O", CultureInfo.InvariantCulture)`, then I'll get a value such as `"2016-06-05T18:39:37.1997258+00:00"` - which I can pass directly to moment without any format specifier.

Hope this helps.
