### ISSUE TITLE
Microsoft Time Zone IDs

### ISSUE THREAD

**Issue by seinavco** [moment/moment-timezone#355]
Hi,

I need to send to the server the browser time zone, and the server knows only these ids : https://msdn.microsoft.com/en-us/library/gg154758.aspx

How can I map between moment time zone name and these ids?

Thanks!

**Comment by mj1856** [comment]
Note that the list you linked to is quite old, and is from WinCE.  I assume you just mean that you're using Windows time zones instead of IANA time zones.

Moment.js doesn't currently support Windows time zones, but there is an open feature request in #281 to do so.

However, consider that it's probably more efficient to convert from IANA to Windows in your server-side code, because the mapping file is yet more data that would have to be loaded into the browser.

Assuming you're server code is in .NET, you can easily convert on the back end using [Noda Time](http://nodatime.org/), with the code I have published [here](http://stackoverflow.com/questions/17348807/how-to-translate-between-windows-and-iana-time-zones).

Then again, if you're going to go to the effort to use Noda Time in your server code, you might as well just use it for working with IANA time zones natively, rather than dealing with Windows time zones at all.  The choice is yours, of course, but in general IANA time zones are preferred.

**Comment by mj1856** [comment]
Just as an update, my .NET [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter) library can be used for this on the back end, without any dependency on Noda Time.
