### ISSUE TITLE
TypeScript: moment and moment-timezone don't play well together

### ISSUE THREAD

**Issue by sfrooster** [moment/moment-timezone#370]
Several things here:
1) moment-timezone doesn't have TS support like moment does (I see this is a separate issue)
2) current moment-timezone definitions don't include format()
3) current moment-timezone definitions fail compilation (MomentTimeZoneFormat is not defined)
4) momentTZ.tz() produces a Moment which is incompatible with moment() (Operator '<=' cannot be applied to types 'Moment' and 'Moment'.)

**Comment by gilmoreorless** [comment]
I know this is an old issue, but for completeness:

* Moment Timezone added type definitions in version `0.5.29`.
* Some type errors between `moment()` and `moment.tz()` are caused by multiple versions of the `moment` package in the dependency tree. See https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905 for more explanation.
