### ISSUE TITLE
(Asia/Tel_Aviv) ,Pacific/Yap and manual offsets(GMT and Etc/GMT) is possible in moment-timezone library?

### ISSUE THREAD

**Issue by gsivaprabu** [moment/moment-timezone#380]
Hi,

Is possible to below time zones are supported in moment-timezone library ?

**1. Asia/Tel_Aviv
2. Pacific/Yap**

Then finally any possible to add **manual offsets of (GMT and Etc/GMT)** ?

Refer the attachment:-

![momenttimezonemap](https://cloud.githubusercontent.com/assets/2444608/18430977/753742ee-78f8-11e6-8361-a8df8fa8fdfa.png)

regards,
[@gsivaprabu](https://github.com/gsivaprabu)

**Comment by mj1856** [comment]
Everything you asked about is already supported by the library:

![image](https://cloud.githubusercontent.com/assets/1396388/19243400/66a8f6b6-8ecc-11e6-9f35-a4a39811d09a.png)

Keep in mind that the interactive world map is a demonstration of one scenario you might need moment-timezone for, but the map image is not what moment-timezone actually provides.  All the dots on the map image are actual zone entries from the `zone.tab` file in the source tzdb data.  The two zones you asked about are actually *links* to other zones.   As far as GMT and the `Etc/*` zones, they are supported as well, but it does not make sense to show them on the map because they are not fixed to a single location.

Sorry for the delayed response.

**Comment by gsivaprabu** [comment]
Thanks lot @mj1856
