### ISSUE TITLE
How to get the exact Date using Time Zone JS - for Australia/Melbourne - Issue with TZ

### ISSUE THREAD

**Issue by rbahadur** [moment/moment-timezone#389]
Hello,

I have a date in our CRM Application and Time Zone is Australia/Melbourne, now in CRM System the Date is in : 10-18-2016 12:15 am (MM-DD-YYYY HH:MM AM).

When I retrieve this date using web Service I will get the date in below format
2016-10-17T16:15:00Z.

Now my question here is how I will get the Date using Moment Time Zone Js exactly what is there in CRM System.

I have tried the below solution 
1 - Get the Date in one variable
   var jun = moment("2016-10-17T16:15:00");
2 - Then find the offset using below method.
   jun.tz('Australia/Melbourne').format('Z z')  = 11
3 - Then add the offset in add hours method.
var b = jun.clone().add(11, 'hours'); 
console.log(b.format()),
Now when I am formatting the above b.format(), I getting the below date
2016-10-18T03:15:00+05:30,
But I need exact date like what is there in Top ie 10-18-2016 12:15 AM.

Can you please suggest some solution to it, we are having a tough time to resolve this issue, as our application is running in multiple region, we need to fix the issues for all.

I am using below JS in our script : 
- moment-with-locales.min.js
-  moment-timezone-with-data.js

Thanks & Regards,
Rah

**Comment by maggiepint** [comment]
If what you are asking is how to get the date and time in Australia for the point in time that you are giving in UTC, it would be this:

```js
moment.tz('2016-10-17T16:15:00Z', 'Australia/Melbourne').format()
"2016-10-18T03:15:00+11:00"
```

Note that because many places in the world do DST, you can't just add or subtract an offset to get a time in a specific region. Instead, you must let the library determine the offset at that time of year.

This blog post might help you: https://maggiepint.com/2016/05/14/moment-js-shows-the-wrong-date/

**Comment by rbahadur** [comment]
Hello Maggiepint,

First of all thank you very much, for the reply and really appreciate the way you have explained the functionality, but I have doubt here, which I am explain below.

The date is now coming fine, but if you see the Time, actual time was  12:15 am, but when you convert the same the time is coming as 03:15, can you please share your input on this, I think we should get the time also 12:15, please let me if  I am wrong here.

**Comment by maggiepint** [comment]
See the section of the blog post about ISO8601.

When you have a date with a ``z`` at the end, it means that the date is in UTC, so ``2016-10-17T16:15:00Z`` is equivalent to ``2016-10-17T16:15:00+00:00``.

When you pass the date into Moment timezone, it converts it from UTC into Melbourne time. Since Melbourne is +11, the time is moved ahead by 11 hours, from 16:15 to 3:15 the next day.

I think that you believe that the local date (Melbourne time) in the database is 10-18-2016 12:15 am

But you state that the web service is returning 2016-10-17T16:15:00Z.

My guess is that your web server is in a UTC-4 time zone. When it sends you the date, it assumes the date is in the local time of the server, and converts it to UTC by adding 4 hours. If in fact the date you are starting with is UTC, then this behavior is wrong and you need to stop it on the web server side. If you get it to send the date as-is, then the code I gave you will work as expected:

```js
moment.tz('10-18-2016 12:15 am', 'MM-DD-YYYY hh:mm a', 'Australia/Melbourne').format()
"2016-10-18T00:15:00+11:00"
```
