### ISSUE TITLE
Incorrect timezone definition.

### ISSUE THREAD

**Issue by Arkanine** [moment/moment-timezone#418]
Hello,
My current position(Cherkassy) is closer to "Europe/Kiev" then "Europe/Zaporozhye", but the result of .tz.guess() returns the "Europe/Zaporozhye" value. Also please clarify the need of use such timezone values as "Europe/Uzhgorod", "Europe/Zaporozhye". In scope of country(for example Ukraine) there is only one actual time zone - "Europe/Kiev".

**Comment by mj1856** [comment]
The guessing algorithm isn't perfect, hence why it's called `guess` rather than `detect`.  I'd be interested in seeing if I could figure out how to improve it though.

Could you tell me your operating system and OS time zone setting?

As to why these exist - all our zones come from [the tz database](https://en.wikipedia.org/wiki/Tz_database), and these are valid identifiers there.  If you want to read the tzdb sources and commentary explaining the three separate zones for Ukraine, you can find that here: https://github.com/eggert/tz/blob/2016i/europe#L3590-L3698

**Comment by Arkanine** [comment]
@mj1856 thank you for the answer, it helps a lot.
operating system - iOS
OS time zone setting 
![screen shot 2016-11-14 at 22 58 58 1](https://cloud.githubusercontent.com/assets/5641601/20282592/12e7a2ee-aabe-11e6-931c-1ce2cab6f116.png)

Is it possible somehow to use http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html subset of tz data?

**Comment by mj1856** [comment]
> Is it possible somehow to use http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html subset of tz data with moment-timezone?

Sure, just go through the list there and filter the data you get from here to those in that list.

However, I recommend against it.  In general, that list isn't very good.  You'll notice there are many zones missing, several zones duplicated, and in general it's arbitrary and not maintained.  See also the very bottom of [the StackOverflow timezone tag wiki](http://stackoverflow.com/tags/timezone/info) about "Rails Time Zone Identifiers".

**Comment by Arkanine** [comment]
@mj1856 thanks!
