### ISSUE TITLE
Time Zone string in Documentation Outdated?

### ISSUE THREAD

**Issue by breadraptor** [moment/moment-timezone#419]
I was trying to output the time currently in another time zone (New York).

Using this:
```
moment.tz.add("America/New_York|EST EDT|50 40|0101|1Lz50 1zb0 Op0"); //taken from Documentation
moment.tz("America/New_York").format('MM/DD/YYYY hh:mm:ss a z');
```
I was getting: 11/15/2016 09:11:39 pm EDT

It's displaying EDT when it should be EST. When I called isDST() it returned false, which is correct. Eventually I switched to using this from the GitHub version for New York:

```
moment.tz.add("America/New_York|EST EDT EWT EPT|50 40 40 40|01010101010101010101010101010101010101010101010102301010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010|-261t0 1nX0 11B0 1nX0 11B0 1qL0 1a10 11z0 1qN0 WL0 1qN0 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1qN0 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1qN0 WL0 1qN0 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1qN0 WL0 1qN0 11z0 1o10 11z0 RB0 8x40 iv0 1o10 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1qN0 WL0 1qN0 11z0 1o10 11z0 1o10 11z0 1o10 11z0 1o10 1fz0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1fz0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1fz0 1a10 1fz0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1fz0 1cN0 1cL0 1cN0 1cL0 s10 1Vz0 LB0 1BX0 1cN0 1fz0 1a10 1fz0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 1cN0 1fz0 1a10 1fz0 1cN0 1cL0 1cN0 1cL0 1cN0 1cL0 14p0 1lb0 14p0 1nX0 11B0 1nX0 11B0 1nX0 14p0 1lb0 14p0 1lb0 14p0 1nX0 11B0 1nX0 11B0 1nX0 14p0 1lb0 14p0 1lb0 14p0 1lb0 14p0 1nX0 11B0 1nX0 11B0 1nX0 14p0 1lb0 14p0 1lb0 14p0 1nX0 11B0 1nX0 11B0 1nX0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Rd0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0 Op0 1zb0|21e6");
moment.tz("America/New_York").format('MM/DD/YYYY hh:mm:ss a z');
```
Gave me: 11/15/2016 08:11:39 pm EST which is correct.

Why didn't the first timezone string work? Does the documentation need to be updated, or was I making some other mistake? I appreciate your patience, I am new to using this library.

Thanks!
Nancy

**Comment by connor-odoherty** [comment]
Could you please tell me what the correct fix is? I don't think switching the string to 'America/New_York|EST EDT|60 50|0101|1Lz50 1zb0 Op0' is scalable. Do you know why it is not picking up on DST properly

**Comment by butterflyhug** [comment]
It's not getting DST properly because you're not using correct DST data.

The docs for `moment.tz.add` are focused on explaining the data format, not necessarily providing current data.  So that string is an out-of-date and limited-duration description of DST in America/New_York.

I believe most folks just use one of the pre-bundled versions of the library that include current data, e.g. moment-timezone-with-data-2010-2020.min.js.  In that case you shouldn't normally need to call `moment.tz.add` at all.  If none of the bundled builds are suitable, you'll probably want to use the build scripts to build a data file specific for your needs, and then use `moment.tz.load`.  I generally wouldn't suggest using `moment.tz.add` unless you have unusual requirements -- it's a pretty low-level API for adding time zone data.

**Comment by maggiepint** [comment]
As opposed to chasing timezone changes, I've put a note in the documentation that the data is sample data and is not up to date, with a link to the up to date data.
