### ISSUE TITLE
Getting wrong date with Brasilia TZ on DTS start day

### ISSUE THREAD

**Issue by Vasse** [moment/moment-timezone#434]
Issue: Getting strange results for TZs where DTS occurs in midnight.

OS: Windows 7
Browser: Firefox 45.0.2 
Time Zone: (UTC -03:00) Brasilia
Date: 1th of September 2016 (any date outside DST)

var momentDate = moment('Oct 16, 2016'); 
log(momentDate.format('lll ZZ'));  //Oct 15, 2016 11:00 PM -0300

Setting date to after DTS: 19th of December 2016
var momentDate = moment('Oct 16, 2016'); 
log(momentDate.format('lll ZZ'));  //Oct 16, 2016 1:00 AM -0200

Is this correct? I would rather get "Oct 16, 2016 1:00 AM -0200" in both cases.

**Comment by maggiepint** [comment]
You have a couple of problems here, but largely this is outside of Moment's control. 

Right now you are parsing a non-supported date format, so you're getting a deprecation warning that says that moment construction falls back to JS Date. You would need to specify the format to deal with this:

```js
moment('Oct 16, 2016', 'MMM DD, YYYY');
```

When you say setting date, do you mean setting the date on your computer? I can't think that that would affect this, given that you are parsing the same date every time. What does affect this is the browser. Different browsers will do different things when presented with an ambiguous DST date. Moment can't work around this in the core library, because the browser does not give us enough timezone information to do so. If you use the moment-timezone library and parse your dates explicitly in the America/Sao_Paulo time zone, the behavior will be consistent.
