### ISSUE TITLE
Timezone Offsets and Abbreviations for GMT-XX to GMT+XX are reversed

### ISSUE THREAD

**Issue by silkentrance** [moment/moment-timezone#436]
The timezone offsets and abbreviations for GMT-XX through GMT+XX are reversed.

It reads

```
    {
      "name": "Etc/GMT+10",
      "abbrs": [
        "-10"
      ],
      "untils": [
        null
      ],
      "offsets": [
        600
      ],
      "population": 0
    },
...    
    {
      "name": "Etc/GMT-10",
      "abbrs": [
        "+10"
      ],
      "untils": [
        null
      ],
      "offsets": [
        -600
      ],
      "population": 0
    },
```

where it should read

```
    {
      "name": "Etc/GMT+10",
      "abbrs": [
        "+10"
      ],
      "untils": [
        null
      ],
      "offsets": [
        -600
      ],
      "population": 0
    },
...    
    {
      "name": "Etc/GMT-10",
      "abbrs": [
        "-10"
      ],
      "untils": [
        null
      ],
      "offsets": [
        600
      ],
      "population": 0
    },
```

Or am I misinterpreting something here?

See also #435

**Comment by silkentrance** [comment]
@maggiepint please respond.

**Comment by silkentrance** [comment]
@maggiepint if this cannot be fixed due to expected legacy behavior, which, in my opinion, is utterly wrong, we should introduce `Etc/UTC+/-N`, see #435.

**Comment by maggiepint** [comment]
We don't add time zones to moment-timezone that are not part of the [IANA time zone database](https://www.iana.org/time-zones). The people who maintain the IANA time zone database have done huge amounts of work over the course of many years to ensure it's accuracy, and we cannot do better.

This particular quirk in the ETC timezones is in the database to allow compatibility with old style POSIX timezones. These zones are only meant to be used by ships at sea. In any case, I'm not sure why you need them for unit tests. Just use a specific time zone.

If you enter a date into Moment-timezone, it will choose the appropriate offset for that time of year. The result of any parse of a date into Moment timezone that includes a date value is deterministic:
```js
moment.tz('2017-01-02', 'America/Los_Angeles').format()
"2017-01-02T00:00:00-08:00"
moment.tz('2017-08-02', 'America/Los_Angeles').format()
"2017-08-02T00:00:00-07:00"
```
That result will not change, no matter what machine I'm running on. If you are passing a date to moment-timezone, and the result is not deterministic, then most likely you are passing a format that moment cannot interpret and construction is falling back to JS Date. You should be receiving a deprecation warning if that is happening.

I really need a working code example to understand why fixed offset zones are necessary. They do not have a practical application in any business domain I'm aware of.

**Comment by mj1856** [comment]
FYI - Both the ships-at-sea and opposite sign are described in the TZDB commentary here: https://github.com/eggert/tz/blob/master/etcetera

**Comment by silkentrance** [comment]
Well, thanks for clearing this up. So somebody at Posix made a mistake and it will carry on into the next millenium, great.

**Comment by mj1856** [comment]
There is no person or organization that is "Posix".  It is a set of standards that goes back to the early years of computing.  The governing body is the IEEE.

It's not even a "mistake".  It's just that the computing world used to be quite different than it is today.  We used to specify time zones with positive offset leading West of UTC instead of East of UTC like we do today.  Or rather, we sometimes did them West, and sometimes did them East.  This was cleared up with the ISO-8601 standard, which the world has slowly been adopting.

If you've ever seen time zones like `PST8PDT` or `CET-1CEST,M3.5.0/2,M10.5.0/3`, those are defined of the POSIX specification.  Note 8 is positive for Pacific, and -1 is negative for Central European Time in the above examples.

https://en.wikipedia.org/wiki/POSIX
https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC


![image](https://cloud.githubusercontent.com/assets/1396388/21650504/f837753c-d259-11e6-85bf-11d02e12cf11.png)
https://xkcd.com/927/

**Comment by JensGabe** [comment]
An example where fixed time zones widely used is in the Medical industry. Here every action needs to be registered with signature and timestamp, either by hand or electronically. As the timestamp at summertime-swtich-time is not specific without further annotation (02:30 with or without DST?), and the amount of computer systems which doesn't handle DST correct, it has become somewhat of an industry standard to do away with DST and use a fixed timezone.
