### ISSUE TITLE
Feature request: Provide DST-neutral abbreviation formats. 

### ISSUE THREAD

**Issue by jaepage** [moment/moment-timezone#439]
More often than not, I'd rather report the DST-neutral abbreviation of a timezone. Such as: 

- PT, not PST or PDT
- ET, not EST or EDT

But do DST-neutral abbreviations exist outside the US? I don't see any on https://www.timeanddate.com/time/zones/, so perhaps this isn't possible. Thank you.

**Comment by mj1856** [comment]
The only abbreviations we have in our data are those from the IANA time zone database.  We don't want to be in the business of researching and inventing them.

To answer your question though, In general, time zone abbreviations are all over the place.

America/Los_Angeles:  PST / PDT == PT
Europe/London:  GMT / BST == (n/a - no such concept)
Europe/Paris:  CET / CEST == CET  (confusing, eh?)

And not even every country has valid abbreviations at all.  In fact, the last several releases of the time zone database, IANA has been removing those that are deemed "invented" or otherwise unsubstantiated with just numeric offsets.

The only source of generic time zone abbreviations I am even aware of is CLDR, and they are deprecated there.

**Comment by jaepage** [comment]
It is unfortunate, yes. Thank you.
