### ISSUE TITLE
Don't break backwards-compatibility with patch releases

### ISSUE THREAD

**Issue by schne324** [moment/moment-timezone#475]
our build script was referencing the path `"node_modules/moment-timezone/builds/moment-timezone-with-data-2010-2020.min.js"` which has been dropped and replaced with `"node_modules/moment-timezone/builds/moment-timezone-with-data-2012-2022.min.js"`. Shouldn't this constitute a minor release?

**Comment by reupen** [comment]
Agreed. Was referencing `moment-timezone-with-data-2010-2020.js` in a Webpack config (and `moment-timezone-with-data-2010-2020.js` is included with the npm distribution).

**Comment by marwahaha** [comment]
As the main maintainer [specified here](https://github.com/moment/moment-timezone/issues/466#issuecomment-291557911):

> WRT breaking changes - please keep in mind that moment-timezone is still 0.x. Per [SemVer #4](http://semver.org/#spec-item-4), anything may change at any time.

We can talk about making these minor releases instead of patch releases, but nothing is fully guaranteed before 1.0 .

Probably, we will just remove the years from the file names at some point so this doesn't continue to break people.
