### ISSUE TITLE
Many timezone abbreviations are missing in v0.5.12

### ISSUE THREAD

**Issue by simon-paris** [moment/moment-timezone#477]
For example, Asia/Singapore, Asia/Kabul, Asia/Ho_Chi_Minh, America/Santiago, etc. Seems like about half are missing.

You can confirm this by opening the library and ctrl+f'ing for "SGT". It should be attached to Singapore but it's missing.

This affects both `moment-timezone-with-data-2012-2022.js` and `moment-timezone-with-data.js` and also data/\*/2017a.json and data/\*/2017b.json.

**Comment by maggiepint** [comment]
This is actually on purpose. The IANA TZDB used to have a practice of basically 'making up' three letter time zone abbreviations when none existed. Because those abbreviations weren't actually used by people in those areas, IANA elected to remove them in the name of accuracy. This thread on the mailing list is one of many on the topic: http://mm.icann.org/pipermail/tz/2017-February/024837.html

Sorry, I know it's a pain for people who relied on them.
