### ISSUE TITLE
Wrong tz name in IE 11 Pacific/Kwajalein

### ISSUE THREAD

**Issue by artemijan** [moment/moment-timezone#482]
moment.tz.guess() in IE 11 returns "Pacific/Kwajalein" if i switched to tz -12 (windows 7). But it's UTC+12

**Comment by mj1856** [comment]
So what is happening here is that UTC-12 is not currently in use by any populated location on Earth.  We have been excluding non-populated zones from the guessing algorithm.

`Pacific/Kwajalein` is on UTC+12 now, but it *used* to be on UTC-12.  It jumped sides of the IDL in August 1993.  Since prior-year offsets are in the guessing algorithm, and no other populated location was ranked higher, it chose that zone.

Including zero-population zones in the guessing algorithm will fix this, as current-year offset carries a higher rank in the algorithm than population.

**Comment by artemijan** [comment]
I guess that in chrome it works because of [Intl impl](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Intl) has timezone and IE doesn't?

**Comment by mj1856** [comment]
Right.  Most browsers [have the Intl time zone support now](http://kangax.github.io/compat-table/esintl/#test-DateTimeFormat_resolvedOptions().timeZone_defaults_to_the_host_environment).

**Comment by isHanz89** [comment]
Hi Matt, 

I having the same issue here. My local computer time zone is set to Kuala Lumpur/Singapore. 
When I use IE, it will show Asia/Manila and if I use Chrome, it work fine. 

Is there any work around for it? 

Thanks,
