### ISSUE TITLE
Breaking change in 0.5.13. The 2010-2020 files are missing.

### ISSUE THREAD

**Issue by nickion** [moment/moment-timezone#493]
After updating to 0.5.13 from 0.5.10, the moment-timezone-with-data-2010-2020.min.js file had been removed and replaced with moment-timezone-with-data-2012-2022.min.js. 

According to semantic versioning rules, a package 0.Y.Z can change at any time and should be considered unstable, therefore this change is permissible. However, moment timezone has had over 30 releases since 2013 and released a production ready status long ago.

I'd like to propose that the version moves from version 0 to X.Y.Z where X > 1, and ask that breaking changes are avoided without the appropriate version number changes, including not removing files from the package that contain code.

**Comment by mj1856** [comment]
I'll be breaking it again before we move to 1.0, because I don't want the year numbers in the file names at all, or we'll have to rev major version numbers every year.

I know people use this in production, but really it is still "at your own risk".  I'm not sure exactly what you mean by "released a production ready status long ago".

Sorry if I broke your build, but I'm still treating this project with 0.x semantics.  I don't plan on making any major changes to the moment.tz interface, but I may indeed iterate over the data file format again before locking it in.  Just FYI.
