### ISSUE TITLE
GMT is wrong

### ISSUE THREAD

**Issue by jonyking** [moment/moment-timezone#512]
When I tried to get a date in my timezone, I only get the date for UTC. 

My code:
```js
var date = moment.tz('2017-07-21 16:10','Europe/Berlin').format(), 
test = moment(date).format("X");
console.log(test);`
```
Also when I tried some variations. My goal is to get the timestamp for the date now.

**Comment by mj1856** [comment]
Unix timestamps are *always* UTC.  That's how they work.

**Comment by jonyking** [comment]
This ja Right. But it should be available to convert to gmt. So the library is useless for timestamps. I need the local timestamp... - You dont get the Problem.

**Comment by mj1856** [comment]
Sorry, no.  I don't get what you are saying the problem is.  Could you please give me exactly what output you get for `test` and exactly what output you expected to get instead?

**Comment by mj1856** [comment]
Note that UTC and GMT are equivalent for most practical purposes.

**Comment by sakthiiv** [comment]
@mj1856 First of all thank you guys for such an awesome library. I have an issue when using format, I have described it below, 

node: v8.5.0
moment-timezone: 0.5.14
moment: 2.20.1
```
momentTz.tz("2018-06-10T11:30:00Z", "Africa/Abidjan").format()
"2018-06-10T11:30:00Z"

momentTz.tz("2018-06-10T11:30:00Z", "America/Argentina/Buenos_Aires").format()
"2018-06-10T08:30:00-03:00"

momentTz.tz("2018-06-10T11:30:00Z", "Africa/Abidjan").format('zz')
"GMT"

momentTz.tz("2018-06-10T11:30:00Z", "America/Argentina/Buenos_Aires").format('zz')
"-03"
```
When using `Africa/Abidjan` the result is `2018-06-10T11:30:00Z` and we don't see the timezone offset. Is this intentional?
If so how do we convert this so that the resulting format has the timezone offset ?
