### ISSUE TITLE
parse utc time

### ISSUE THREAD

**Issue by Luncher** [moment/moment-timezone#549]
input: `moment("Wed, 18 Oct 2017 09:45:39 +0800").utc()`

output: 

`moment.utc("2017-10-18T09:45:39.000+00:00")`

----

I want to know why the output is not： `moment.utc("2017-10-18T09:45:39.000+00:00")`

**Comment by mj1856** [comment]
I'm not sure what you are asking. Your said output and expected output are the same, but also you are describing them in terms of code rather than output values.

How are you evaluating them? If you are looking at `_d` or `_i`, then you are doing the wrong thing.  You should call a function, such as `format` or `toISOString`, etc.

Also note that `2017-10-18T09:45:39.000+08:00`  is equivalent to `2017-10-18T01:45:39.000Z`, which is the output of:

```js
moment("Wed, 18 Oct 2017 09:45:39 +0800").utc().format()
//=>  "2017-10-18T01:45:39Z"
```
