### ISSUE TITLE
Inconsistent time behaviour with YYYY-MM-DD string

### ISSUE THREAD

**Issue by wyqydsyq** [moment/moment-timezone#556]
```
moment.tz('2017-10-31').format()
→ "2017-10-31T01:29:04Z"
moment.tz('2017-10-31', 'Australia/Sydney').format()
→ "2017-10-31T00:00:00+11:00"
```

Why does specifying the timezone result in the time (`1:29:04`) being stripped, but not specifying the timezone retains the current time offset on top of the parsed date?

This behaviour is inconsistent and confusing.

**Comment by mj1856** [comment]
Calling `moment.tz` with a single argument is intended to return the current time in the time zone with that name.  For example:  `moment.tz('Australia/Sydney')`.

Since you're passing a string in that parameter that is not a time zone name, you'll see an error in the console output:

> Moment Timezone has no data for 2017-10-31. See http://momentjs.com/timezone/docs/#/data-loading/.

It's thinking you meant `'2017-10-31'` to be the time zone name.

The return value is just the current UTC time.  After all, the operation you asked for was to get the current time, in some unknown time zone, so the best we could do is return the UTC time.  The only other option would be to throw a hard error.
