### ISSUE TITLE
Offset bug in Africa/Ceuta in 1970?

### ISSUE THREAD

**Issue by santillaner** [moment/moment-timezone#564]
According to Webkit in Mac OS X (Chrome & Safari), Africa/Ceuta's offset at the epoch (1st Jan 1970) is -60, while moment-timezone says it's 0. ¿Is it a moment-timezone bug? ¿or a Webkit one?

**Comment by mj1856** [comment]
0 is correct

https://www.timeanddate.com/time/zone/spain/ceuta?year=1970

What code gave you -60?

Note that ECMAScript 5.1 and lower used to require that only the *current* tz/dst rule be used regardless of date.  This was fixed in ECMAScript 6.  Most modern browsers have implemented the change.  Not sure about safari.

Also, note that Chrome and Safari use different JS engines.  While Safari I uses JavaScriptCore from WebKit, Chrome uses V8.  So it may be a bug in JavaScriptCore, but you shouldn't see the same bug in Chrome.
