### ISSUE TITLE
Wrong date format parsing

### ISSUE THREAD

**Issue by oleg-koval** [moment/moment-timezone#568]
## problem
Date parsing using moment.tz
`const format = moment.tz(dateString, format, timezone)`

## input
`'09-30-2017 9:32'` as dateString
`'M/D/YY h:mm'` as format and
`'Europe/Amsterdam'` as timezone

## result
`moment.parseZone("2020-09-30T09:32:00.000+02:00")`

`format.isValid()` is `true`, should be `false`

## code snippet
https://runkit.com/oleg-koval/5a323c614c48b90013f1a8e7

## workaround
just use luxon:
`DateTime.fromString(input, format, locale)`

**Comment by mj1856** [comment]
If I understand you correctly, you're asking why:

```js
moment.tz('09-30-2017 9:32', 'M/D/YY h:mm', 'Europe/Amsterdam').isValid()  === true
```

This isn't a moment-timezone issue, but related to moment's default parsing mode is *forgiving* rather than *strict*.  You can learn more about this here: http://momentjs.com/guides/#/parsing/strict-mode/

Pass true as the third parameter to enable strict mode, then pass the time zone in the last parameter.

```js
moment.tz('09-30-2017 9:32', 'M/D/YY h:mm', true, 'Europe/Amsterdam').isValid()  === false
```

**Comment by oleg-koval** [comment]
@mj1856 thanks for information :)
