### ISSUE TITLE
How to work with moment.tz for an old date time value

### ISSUE THREAD

**Issue by tsabbay** [moment/moment-timezone#619]
Hello (:,

Seems like when using moment.tz for 2010-2020 all is well.
while working with old date time, for example 1983 i see that the day light saving is not responding well.
actually, every date with year prior to 2010 and after 2020 will not respond well to time zone changes.

my first work around is to set 2010 year to grab a "correct" (more accurate) time offset.

any thoughts ?

**Comment by ellenaua** [comment]
Hi @tsabbay does that happen in browser or on server (node.js)?
Could you please provide a code which reproduces this error? 
Which version of moment-timezone do you use?
Does that happen for all timezones, or for some particular?

**Comment by tsabbay** [comment]
hi @ellenaua its happening on both client/server
and in all major browsers.

**Comment by gilmoreorless** [comment]
My suspicion is that this is caused by using a limited set of data. Moment Timezone provides multiple versions of the build with different data ranges: https://github.com/moment/moment-timezone/tree/develop/builds

Try using one of the alternative builds to get a wider date range. If you're still having problems we can re-open this issue.
