### ISSUE TITLE
Etc/GMT+x or Etc/GMT-x works backwards

### ISSUE THREAD

**Issue by aviramga** [moment/moment-timezone#656]
When entering Etc/GMT+x or Etc/GMT-x as values for in moment.tz(), the Etc/GMT+x will actually display the Etc/GMT-x value and vise versa. 

For example:
moment.tz("Etc/GMT-2") => 2018-07-18 10:03:16
moment.tz("Etc/GMT+2") => 2018-07-18 14:03:16

You would expect the opposite results

**Comment by Sviatoy** [comment]
Etc/GMT-2 !== GMT-2
https://opensource.apple.com/source/system_cmds/system_cmds-230/zic.tproj/datfiles/etcetera

**Comment by kjguruprasad** [comment]
Hi,
source: https://en.wikipedia.org/wiki/Tz_database

The special area of "Etc" is used for some administrative zones, particularly for "Etc/UTC" which represents Coordinated Universal Time. In order to conform with the POSIX style, those zone names beginning with "Etc/GMT" have their sign reversed from the standard ISO 8601 convention. In the "Etc" area, zones west of GMT have a positive sign and those east have a negative sign in their name (e.g "Etc/GMT-14" is 14 hours ahead of GMT.)
Hope above explanation from wikipedia answers your query.
