### ISSUE TITLE
Acc to doc moment.tz("2013-11-18 11:55", "America/Toronto").format() should give "2013-11-18T11:55:00-05:00" but gives "2013-11-18T11:55:00Z"

### ISSUE THREAD

**Issue by DerGuteWolf** [moment/moment-timezone#661]
cf http://momentjs.com/timezone/docs/#/using-timezones/ :
moment.tz("2013-11-18 11:55", "America/Toronto").format() should give "2013-11-18T11:55:00-05:00" but gives "2013-11-18T11:55:00Z", cf. http://jsfiddle.net/3xpbLr2t/

**Comment by DerGuteWolf** [comment]
Any update here?

**Comment by DerGuteWolf** [comment]
Is this a bug or is the documentation wrong?

**Comment by gilmoreorless** [comment]
Your JSFiddle link isn't loading the time zone data correctly. It's trying to load from http://bestkirdape.freeiz.com/timezone/moment-timezone-data.js, which isn't an official data source, and currently doesn't work.
The browser console shows a warning of `Moment Timezone has no data for America/Toronto.`.

Using the file https://momentjs.com/downloads/moment-timezone-with-data-10-year-range.min.js instead of `moment-timezone.min.js` should load the data correctly.
