### ISSUE TITLE
Performance difference between `moment.tz(time, zone)` and `moment(time).tz(zone)`

### ISSUE THREAD

**Issue by nonrenewable-zz** [moment/moment-timezone#670]
It seems that performance-wise constructing a moment object for a timestamp and Date make more sense as `moment(time).tz(zone)` by a significant amount (see perf numbers and code used to generate below). Is this expected? According to the documentation the two statements should be equivalent so would it be ok for them to be used interchangeably or are they doing something different? 

Timings:
```
constructor: 12934.047ms
3897102530340612000
tz: 9329.612ms
3897102530340612000
```

Libs versions:
```
> moment.version
'2.22.2'
> moment.tz.version
'0.5.21'
```

Code used to generate results:
```
const moment = require("moment-timezone");
const MAX_TIME = 1536862426000;
const MIN_TIME = 22097626000;
const DIFF_TIME = MAX_TIME - MIN_TIME;
const times = [];
const ZONES = ["America/Los_Angeles", "America/Chicago", "America/New_York"];
function get_times(){
    for(let i = 0; i < 5000000; i++){
	const value = i%( (ZONES.length) - 1 );
	times.push({time: Math.round(Math.random() * DIFF_TIME) + MIN_TIME,
		    zone: ZONES[value]
		   });
    }
}

get_times();

{
  console.time("constructor");
  // Do things here
  let foo = 0;
  for(const item of times) {
    const time = item.time;
    const zone = item.zone;
    foo += moment.tz(time, zone).valueOf();
  }
  console.timeEnd("constructor");
  console.log(foo);
}

{
  console.time("tz");
  // Do things here
  let foo = 0;
  for(const item of times) {
    const time = item.time;
    const zone = item.zone;
    foo += moment(time).tz(zone).valueOf();
  }
  console.timeEnd("tz");
  console.log(foo);
}
```

**Comment by gilmoreorless** [comment]
I found some time to dig into this, and you're right that there's a performance difference (even on the latest `0.5.43` release).

The reason why is due to variable input formats:

1. For numeric timestamps, like your test samples, the behaviour of `moment.tz(a, b)` and `moment(a).tz(b)` is exactly the same. (In fact, the first method calls the second method internally.)
2. But for string inputs, there is a slight difference. A string can be provided to `moment.tz()` that has an embedded time zone, and that needs some extra work to convert the time differences. It's this extra work (and deciding if it even needs to be done) that results in the different timing results you've seen.

I did find a small possible optimisation though, which I've committed in dffed7a. This should slightly reduce the time difference between the two methods for numeric timestamps. (Although it hasn't been released yet.)
