### ISSUE TITLE
Invalid time offset for China since there is one single timezone

### ISSUE THREAD

**Issue by mbm-rafal** [moment/moment-timezone#674]
Since there is a single time offset in entire China
https://en.wikipedia.org/wiki/Time_in_China

when using moment library for different time zones (based on PHP entires) like:

```
moment.tz('2016-01-01', 'Asia/Shanghai').format('ZZ'),
moment.tz('2016-01-01', 'Asia/Urumqi').format('ZZ')
```

even though they should be UTC +8

there is +8:00 and +6:00 because of geo offset

![image](https://user-images.githubusercontent.com/19263109/46293461-e05f3380-c593-11e8-9b0e-56ed30f3b064.png)

**Comment by kaiwen-lin** [comment]
I think this is one of those gray areas where two timezones exist in the same physical location. As a rough rule, the timezone used in Urumqi largely depends on the application or ethnicity of the person.
https://en.wikipedia.org/wiki/Xinjiang_Time

Since the timezone data used for moment-timezone is from IANA, their database has set Asia/Urumqi to +06:00 and is not really a problem with moment-timezone.

I hope this helps?

**Comment by mbm-rafal** [comment]
@kaiwen-lin thank you. I didn't know about this another exception. Thanks a lot!
