### ISSUE TITLE
Wrong offset for 'Africa/El_Aaiun'

### ISSUE THREAD

**Issue by sophiatca** [moment/moment-timezone#695]
vanilla javasciprt for 'new Date('Oct 31 2018 12:00:00').toLocaleString("en-US", {timeZone: "Africa/El_Aaiun"})' returns "10/31/2018, 4:00:00 PM"
but moment('Oct 31 2018 12:00:00').tz('Africa/El_Aaiun') returns "10/31/2018, 5:00:00 PM"
because offset for El_Aaiun is +60

Google result for for Africa/El Aaiun is Western European Standard (GMT)with offset 0. 

I'm not sure if there's other wrong data

**Comment by mj1856** [comment]
Like `Africa/Casablanca`, this zone is affected by the Morocco time zone change which puts Morocco on UTC+1 permanently.  This is part of the 2018g data update.
- https://www.timeanddate.com/news/time/morocco-abolishes-time-changes.html
- https://www.timeanddate.com/time/zone/western-sahara/el-aaiun
- https://mm.icann.org/pipermail/tz-announce/2018-October/000052.html

You are seeing different results with `toLocaleString` (part of the ECMAScript Intl API) because the Moroccan government made this change with only two days warning, so many web browsers, computers, mobile devices, etc. are not yet updated.
