### ISSUE TITLE
_z abbrs are incorrect after version 0.5.11

### ISSUE THREAD

**Issue by peterneely** [moment/moment-timezone#723]
Steps to reproduce:

Create a moment date with the timezone set to 'America/Argentina/Buenos_Aires'.
Call `zoneAbbr()` on that date.
The timezone abbreviation should be 'ART', not '-03'.

```
const date = moment.tz('America/Argentina/Buenos_Aires');
const abbr = date.zoneAbbr();
console.log(abbr);
```

This and many other timezone abbreviations are incorrect in moment-timezone after version 0.5.11.

See screenshot below of the incorrect abbreviations (under _z > abbrs):

![screen shot 2019-01-30 at 10 21 07 am](https://user-images.githubusercontent.com/5221440/52003532-a5a1d500-2479-11e9-9f92-3881ac257ab3.png)

**Comment by jdiamond** [comment]
0.5.11 was using the 2016j version of the time zone database. In 0.5.12, the database was upgraded to 2017b. If you download the data for the 2016j and 2017a releases and compare the record for America/Argentina/Buenos_Aires, you can see the ART abbreviation disappeared. This change seems to be intentional:

https://github.com/eggert/tz/commit/c9e6ef07cc6f1062ddd032c96c5172f403c0058f

It's an unfortunate loss of functionality. Does anybody know of any alternatives?

**Comment by mj1856** [comment]
Many time zone abbreviations have been removed from IANA.  If you want to make the case that they are real and actually used, the place to do so is on the IANA tz database discussion list.

https://mm.icann.org/mailman/listinfo/tz

Some abbreviations may be found in CLDR as well

http://cldr.unicode.org/

But in general, time zone abbreviations are a messy thing.  Much of the world does not even use them, and they aren't even used consistently where they are used.
