### ISSUE TITLE
Lisbon utcOffset is incorrect

### ISSUE THREAD

**Issue by jiajie8362** [moment/moment-timezone#732]
Hi,
 
I want to get the city's utcOffset, but when I use  moment.tz.zone('Europe/Lisbon').utcOffset(0), it always return -60.  I saw the time in Lisbon is correct on the http://momentjs.cn/timezone/ website.

Anything wrong with my usage?

Thanks.

**Comment by mj1856** [comment]
At timestamp `0` (equal to 1970-01-01 00:00:00.000 UTC), Lisbon was at UTC+1.  Thus you get -60, because that method returns offsets in minutes west of GMT.

You probably meant:

```js
moment.tz('Europe/Lisbon').utcOffset()
```

Which returns `60`, when run today (UTC+1 as minutes *east* of GMT), and would have returned 0 on March 16th when you reported this issue, since DST in Lisbon began on March 31st this year.
