### ISSUE TITLE
Behaviour change between 0.5.23 & 0.5.25 concerning timezone offset

### ISSUE THREAD

**Issue by SouquieresAdam** [moment/moment-timezone#744]
The value for the current expression is not the same since 0.5.24 :
`moment.parseZone(moment.tz(moment('2017-01-01T18:42:02+00:00').format('YYYY-MM-DD HH:mm:ss'), "Asia/Dubai")).utcOffset()
`

**Jsfiddle with 0.5.23 :** 

http://jsfiddle.net/Lfmda0zn/
 **returns 240**

**JsFiddle with 0.5.25 :**

http://jsfiddle.net/0x7rmpt8/7/
**returns 0**

I expect 240 to be the result in this case. It's the offset between "Asia/Dubai" & "UTC" on 2017-01-01

**Comment by mj1856** [comment]
Your code is parsing a string, formatting it as local time, parsing it again in a time zone, then passing that moment object to `parseZone`, which is a function designed to take a string.  Such convoluted steps are not necessary or supported.

If you want the offset between Asia/Dubai and UTC given a string containing a specific offset like the one you showed:
```js
moment.tz('2017-01-01T18:42:02+00:00','Asia/Dubai').utcOffset() //=> 240
```

If you don't have the offset in the string, but the value is known to be in UTC, then:
```js
moment.utc('2017-01-01T18:42:02').tz('Asia/Dubai').utcOffset() //=> 240
```

If you don't have the offset in the string, but the value is known to be in the local time of the timezone provided, then:
```js
moment.tz('2017-01-01T18:42:02','Asia/Dubai').utcOffset() //=> 240
```

As far as the change you demonstrated, it simply shows that if you pass a `Moment` object into `parseZone` that has a time zone, that it will strip the time zone when cloning.  Since `parseZone` isn't documented to accept a `Moment` object, then the behavior is undefined anyway.  So simply - don't.

Thanks.
