### ISSUE TITLE
Timezone taking default time of date

### ISSUE THREAD

**Issue by theromie** [moment/moment-timezone#746]
I am trying to convert datetime to current timezone but its giving default time of date.
`var timeAgo = moment(date).tz("Asia/Kolkata");
 console.log({date, timeAgo});
  return timeAgo.fromNow();  `

output of console
`{date: "2019-04-24 8:49:15"
timeAgo: Moment
_ambigTime: false
_ambigZone: false
_d: Wed Apr 24 2019 14:19:15 GMT+0530 (India Standard Time) {}
_i: "2019-04-24 8:49:15"
_isAMomentObject: true
_isUTC: true
_isValid: true
_locale: Locale {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", ordinal: ƒ, _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/, …}
_offset: 330
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -2, charsLeftOver: 0, …}
_z: Zone {name: "Asia/Kolkata", abbrs: Array(8), untils: Array(8), offsets: Array(8), population: 15000000}
__proto__: Object
__proto__: Object}`

**Comment by ichernev** [comment]
I'm sorry, when you print moment objects, better use `format()` or `toISOString()`. Deciphering this crap is almost impossible, and then you get your own ideas of what `_d` means, and you're likely wrong (because it's complicated).

Reopen if you can report in a clean way what is the expected and actual behavior.
