### ISSUE TITLE
guess() method returns Asia/Manila when the timezone is Australia/Perth

### ISSUE THREAD

**Issue by niyaza3** [moment/moment-timezone#748]
In internet explorer guess() is returning Asia/Manila instead of Australia/Perth.

**Comment by ichernev** [comment]
Try to figure out if guess is using Intl (not sure if IE has Intl), or not. If guess is using our custom "smart" implementation, then check how different these timezones are. Also, it's possible IE is buggy and reports wrong offsets which confuse moment-timezone.

There is a reason it's called `guess` and not `getTimezone`, because its best effort and could fail for a number of reasons.

Closing this in favor of #873.
