### ISSUE TITLE
Bundle sizes?

### ISSUE THREAD

**Issue by corysimmons** [moment/moment-timezone#759]
How big is this when bundled with Webpack? I've heard horror stories about Moment causing bundles to blow up. Does this include Moment in bundles?

If it is a pretty significant increase in bundle size, can Luxon do something similar to this:

```js
var june = moment("2014-06-01T12:00:00Z")
june.tz('America/Los_Angeles').format('ha z')
```

...without the big bundle size?

Thank you.

**Comment by gilmoreorless** [comment]
By default, webpack will include all Moment locales AND all Moment Timezone zone definition data, because it doesn't know which locales/data you'll use at runtime. All up, including the libraries themselves, this can add up to over 1 MB of minified JS, or around 105 KB minified + gzipped (the repetitive zone data compresses very well).

There are some webpack plugins that can help strip out unneeded locales and zone data:

* [https://www.npmjs.com/package/moment-locales-webpack-plugin](moment-locales-webpack-plugin)
* [https://www.npmjs.com/package/moment-timezone-data-webpack-plugin](moment-timezone-data-webpack-plugin) _(disclosure: I wrote this one)_

Together they can bring the bundled JS down to around 60 KB minified, or 20 KB minified + gzipped, depending on the configuration and your data needs. ([See some example stats here.](https://www.npmjs.com/package/moment-timezone-data-webpack-plugin#example))

I can't answer the question about Luxon though, so I'll leave that to others.

**Comment by corysimmons** [comment]
Awesome thank you. I'll Star your lib for when I need historical timezone data without the MB of js.

To answer my own question about if Luxon can do this (at a fraction of the size of Moment, but without historical timezone data—and an uglier API):

```js
// moment-timezone
const moment = require('moment-timezone')
moment().utc().tz('America/Los_Angeles').format('ha z')

// ===

// luxon
const { DateTime } = require('luxon')
DateTime.fromISO(DateTime.utc(), { zone: 'America/Los_Angeles' }).toFormat('ha ZZZZ')
```
