### ISSUE TITLE
`moment.tz` constructor doesn't take all the same arguments as the `moment` constructor

### ISSUE THREAD

**Issue by hefler** [moment/moment-timezone#761]
The doc states:

> The moment.tz constructor takes all the same arguments as the moment constructor, but uses the last argument as a time zone identifier.

However it fails to parse ISO 8601 strings such as:
> 2013-039    # An ordinal date part
> 2013-W06-5 09  # A week date part and hour time part
> 2013-039 09    # An ordinal date part and hour time part

It this a bug in `moment.tz` or in the docs?

Example:
https://jsfiddle.net/25rx4sto/

**Comment by MartinManev** [comment]
You are talking about the date string, which is one of the possible arguments. The docs are correct in the sense that the function can take the same number or type of arguments. The problem here is that the parser for moment.tz doesn't understand these particular date strings. I'm no expert here to say if this is the correct behavior or not, but for me, I always specify the format that I expect the date string to be in like so:

```
const TIMEZONE = 'Europe/Sofia';
const USE_STRICT = true;
moment.tz('2019-03-31T00:00:00Z', moment.ISO_8601, USE_STRICT, TIMEZONE);
```

For the second argument read this: https://momentjs.com/guides/#/parsing/known-formats/
For the third argument read this: https://momentjs.com/guides/#/parsing/strict-mode/
The last argument is the time zone, which is the only argument added by moment-timezone.

See if you can provide a built-in or custom format and enforce strictness for the time being.

**Comment by ellenaua** [comment]
```moment.tz('2013-W06-5 09', 'America/New_York').format()```
returns ```2013-02-08T09:00:00-05:00```
```moment.tz('2013-039 09', 'America/New_York').format());```
returns ```2013-02-08T09:00:00-05:00```

**Comment by hefler** [comment]
Thank y'all for the clarifications.
