### ISSUE TITLE
moment.tz.setDefault per request rather than whole application

### ISSUE THREAD

**Issue by thellimist** [moment/moment-timezone#820]
I'm trying to find a way in express to do (100s) of time operations for each request where the calculations should be based on the users' timezone. Basically rather than having `moment(myDate).tz(timezone)` for 100s of places, is there a way to make the `setDefault()` function work per express request session rather than per application?

**Comment by ellenaua** [comment]
Yep, this is highly requested feature, we'll check what can be done.

**Comment by ichernev** [comment]
@thellimist first of all, ideally you should use `moment.tz(..., timezone)`, because it's the most accurate (the other creates in "server-local" first then transfers it to timezone). Second, this could be easily handled by your own code (i.e just stick the timezone in the session and then have a helper method `momentTz(...)` that passes args to `moment.tz(..., session.timezone)`.

What we can do about it -- make some template moment in a given timezone and then "clone + parse" it to use the same timezone? It doesn't seem clean, I think what I described above is much cleaner.
