### ISSUE TITLE
Remove unused/deprecated timezones

### ISSUE THREAD

**Issue by HZ-labs** [moment/moment-timezone#828]
Exp: Asia/Saigon
Reason - https://www.php.net/manual/en/timezones.others.php

**Comment by AndriyHromyak** [comment]
Guys, do you have an option to allow only canonical timezones f.e. when using guess? 
- moment.tz.guess();

A lot of services now do not allow non-canonical timezone and often it leads either to crushes or broken data for analytics. Can i ask to look in to it? Because right now we forced use mapings and stuff

**Comment by ichernev** [comment]
The timezones we have come from IANA. Currently IANA can't really figure out which are "canonical" and which are not, so we're not going to maintain a list of broken timezones, to support this feature.

If you feel like you understand the problem well, just join the IANA mailing list and sort the issue there, for all users (OSes, libraries, languages, etc etc)

**Comment by sgn** [comment]
Well, I still have `TZ=Asia/Saigon` set in my environment variables.
