### ISSUE TITLE
Timestamp for system timezone (Windows 7, Node 11)

### ISSUE THREAD

**Issue by d-adamkiewicz** [moment/moment-timezone#844]
Dirty way,  im struggling to write it better, any ideas?:

```js
// file: moment-timezone.test.js
const moment = require("moment-timezone");
let zone = process.argv[2] || "Europe/Warsaw";
let n = new Date(moment().tz(zone)._d).getTime();
console.log(n, new Date(n));
```
```dos
C:\tests>node moment-timezone.test Europe/Warsaw && time /T
1589364738183 2020-05-13T10:12:18.183Z
10:12
```

**Comment by ellenaua** [comment]
Timestamp does not depend on timezone. You can just do new Date().getTime() and in ANY timezone it will be the same value. I'll write article about that because lot of developers think timestamp depends on timezone

**Comment by d-adamkiewicz** [comment]
```js
// moment-timezone.1.test.js
const moment = require("moment-timezone");
let zones = ['Europe/London', 'Europe/Warsaw', 'Europe/Moscow'];
zones.forEach(z => {
        let n = new Date(moment().tz(z)._d).getTime();
        console.log(z, n, new Date(n));
});
```
```dos
C:\tests/>node moment-timezone.1.test && time /T
Europe/London 1589785132352 2020-05-18T06:58:52.352Z
Europe/Warsaw 1589788732365 2020-05-18T07:58:52.365Z
Europe/Moscow 1589792332367 2020-05-18T08:58:52.367Z
07:58
```
In the code above I'm setting different timezones and I'm getting different timestamps ... as expected.  The problem is the use of non-public (?) `._d` property ... can I avoid it and use some public method instead ?

**Comment by gilmoreorless** [comment]
You're getting different results because the `._d` property is manipulated within Moment for different purposes. From the [Internal Properties guide](https://momentjs.com/guides/#/lib-concepts/internal-properties/):

> Frequently, developers are confused by console output of the value of `_d`.
Moment uses a technique called epoch shifting that causes this property to sometimes differ from the actual date value that the Moment reflects.
In particular if Moment TimeZone is in use, this property will almost never be the same as the actual value that Moment will output from its public `.format()` function.
As such, the values of `_d` and any other properties prefixed with `_` should not be used for any purpose.

@ellenaua is correct — a timestamp is separate from a timezone. I'm not entirely sure what your use case is here, could you clarify a little? If you're just trying to get the system's current time, `new Date()` will give you that without needing Moment.

**Comment by d-adamkiewicz** [comment]
All I need is public reliable method that takes zone and returns value that is (in current version of moment timezone) set to  ._d property. Ok. I understand that timestamp calculated using it is not by definition real timestamp, but its useful in my case where I can store date and time as numeric value that can be easily presented as  date and time of specific timezone

**Comment by ichernev** [comment]
@d-adamkiewicz first of all, ignore the `_d` property, as if it doesn't exist. It is not part of the official API and it is not documented. It could be removed,renamed at any point, and no complaining will get it back.

Now about what you need -- a "timestamp", something like `1589785132352` is number of milliseconds since Jan 1st 1970 **in UTC**. So if you store that you won't have any info on the timezone which it was "recorded"/"timestamped" in, but the time will be correct (i.e if you convert it to the same timezone, it would be accurate).

You could store the offset, like what format() outputs: `'2022-08-26T06:59:18-07:00'` (the -07:00), but that doesn't capture the actual zone, just the offset (offset is how much a given timestamp differs from UTC, and a zone is a set of rules about changing offsets due to DST and goverments doing stuff).

So if you want to have all the data, ideally you'll record the timestamp+offset + timezone, so `America/Los_Angeles` + `'2022-08-26T07:02:33-07:00'`, so you know the date, time, offset and timezone (during DST it is possible to have 2 different times with same components and different offsets).

You could also have timestamp + timezone, like `1661522553000` + `America/Los_Angeles`. Of course in both cases the other end (reading this data) needs to have support for timezones.
