### ISSUE TITLE
utcOffset returns different values for the same date but different time

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [moment/moment-timezone#870]
Steps to reproduce:
1. set your time zone to PDT, eg. Los-Angeles
2. execute the following code

```js
const strDate = '2020-10-31 23:59:59';
const targetTZ = 'America/New_York';

console.log(moment.tz(strDate, targetTZ).utcOffset()); // -240
console.log(moment.tz(strDate, targetTZ).startOf('day').utcOffset()); // -240

console.log(moment.tz(new Date(strDate), targetTZ).utcOffset()); // -300
console.log(moment.tz(new Date(strDate), targetTZ).startOf('day').utcOffset()); // -240

console.log(moment.tz(moment(strDate), targetTZ).utcOffset()); // -300
console.log(moment.tz(moment(strDate), targetTZ).startOf('day').utcOffset()); // -240
```

This is the case when browser's time zone is PDT and target time zone is EST.
When not in PDT but PDT is set to be the default time zone, ie `moment.tz.setDefault("America/Los_Angeles");` then the case with `new Date(strDate)` is working as expected but `moment(strDate)` case is still inconsistent.
Setting `strDate` to `'2020-10-31 23:59:59Z'` makes all 3 cases to return same value - `-240`.

**Comment by mongoose700** [comment]
This is the expected behavior.

When you do `moment.tz(strDate, targetTZ)`, you are telling it to create a moment that has the local time of `strDate` in `targetTZ`, so you get `2020-10-31 23:59:59-04:00`.

When you do `moment.tz(new Date(strDate), targetTZ)`, the `new Date(strDate)` creates a `Date` with your browser's time zone and a local time of `2020-10-31 23:59:59`, which would be `2020-10-31 23:59:59-07:00`. The `moment.tz(..., targetTZ)` then converts that time to the time zone without persisting the local time, so you get `2020-11-01 01:59:59-05:00`.

Doing `moment.tz(moment(strDate), targetTZ)` is essentially the same as the `moment.tz(new Date(strDate), targetTZ)` case. The difference here is that `moment(strDate)` will use the default time zone you've set with `moment.tz.setDefault("America/Los_Angeles")` if you've done so, instead of always falling back to the browser time zone. So if you haven't set the default time zone, it will behave the same as `new Date(...)`.
