### ISSUE TITLE
get time depending upon long form time zone name

### ISSUE THREAD

**Issue by SanthoshBanavath** [moment/moment-timezone#890]
Can we have the functionality to use the full timezone name (`Eastern Standard Time`, `India Standard Time`...etc)?
`moment.tz('India Standard Time')` for UTC+5:30 and so on.

**Comment by SanthoshBanavath** [comment]
I have the data in the standard time zone but not country wise. Like instead of `Asia/Kolkata`, I have `India Standard Time`. Is it possible to get the timezone based on the full timezone name?

**Comment by icellan** [comment]
This should really be in the list of timezones

**Comment by siosism** [comment]
India is a pretty large part of the world. Don't know why this isn't already included? Voting +1 for getting this added.

**Comment by gilmoreorless** [comment]
> India is a pretty large part of the world. Don't know why this isn't already included? Voting +1 for getting this added.

@siosism This issue isn't about adding data for India; that's already available by using the id `Asia/Kolkata`.

From what I can see, this issue is about getting existing data by using different input strings, effectively as aliases. Unfortunately, as detailed in https://github.com/moment/moment-timezone/issues/760#issuecomment-765877778, these long-form names aren't available in the IANA time zone database that Moment Timezone relies on. Partly this is because the names change per locale. For example:

| Locale | Name |
|-|-|
| `en` (English) | India Standard Time |
| `es` (Spanish) | hora estándar de la India |
| `fr` (French) | heure de l’Inde |
| `de` (German) | Indische Zeit |

To get this data into Moment Timezone correctly would require integrating the [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/). This is not a simple task, and my guess is it's way out of scope for the [maintenance-only  status of this project](https://momentjs.com/docs/#/-project-status/).

**Comment by ichernev** [comment]
If you insist, just use the moment.tz.link feature and add aliases yourself (for your project), just don't expect us to maintain such a list.
