### ISSUE TITLE
No change when setDefault() unless remount component

### ISSUE THREAD

**Issue by a-salimkhanov** [moment/moment-timezone#896]
1. Loaded component A
2. All the dates it contains, formatted according to the default timezone
3. Next step - Component B changes default timezone ( this.$moment.tz.setDefault('Europe/London') )
4. The component A still has old formatted dates, unless it's reloaded (remounted)

Is there a way to to make the changes take effect immediately according to new default timezone? 
Using Vue, by the way.
Thanks

**Comment by ichernev** [comment]
Thank you for explaining how setDefault works: https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/

> Subsequent calls to `moment.tz.setDefault` will not affect existing moment objects or their clones.

Also not sure which framework that is, but after you change all moment objects (you can add a function that sets the timezone to the default timezone), you have to reload them anyway (otherwise UI won't know it changed).
