### ISSUE TITLE
Incorrect time zone for Athens (One hour ahead)

### ISSUE THREAD

**Issue by Mahan-F** [moment/moment-timezone#929]
### Moment-timezone version which you use: 

Version: 0.5.33 (latest)

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
The time returned for the `Europe/Athens` time zone is in correct. Athens time zone is UTC +02:00 while moment is giving the time in UTC+03:00. I'm not sure if this is a bug with DST since in summer time when DST is active, Athens time zone is UTC+03:00.

`moment('2020-05-18T00:00:00Z').tz('Europe/Athens').format()`
Returns 
`2020-05-18T03:00:00+03:00`

I noticed similar issue in #904 however I have the latest versions of moment and moment-timezone installed.

**Comment by gilmoreorless** [comment]
> I'm not sure if this is a bug with DST since in summer time when DST is active, Athens time zone is UTC+03:00

It's not a bug, you've described the correct behaviour. :smile:
Athens has a base offset of UTC+02:00, but from the end of March to the end of October, one hour of DST makes its offset UTC+03:00.

Since `2020-05-18T00:00:00Z` is in the DST period for Athens, the returned result is in UTC+03:00. Midnight UTC is 3am in Athens in May.

**Comment by Mahan-F** [comment]
You are definitely right... Now I feel stupid 😄 Thanks for the help!
