### ISSUE TITLE
All old versions requires "moment": ">= 2.9.0"

### ISSUE THREAD

**Issue by yutong-huang** [moment/moment-timezone#933]
### Moment-timezone version which you use:

Version: 0.5.23

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
All the older versions requires the latest version `moment` dependencies. We are using the old version of `moment-timezone` because we can't upgrade `moment` to the latest version. Is there a specific reason for this?

**Comment by ichernev** [comment]
You want to use moment BEFORE 2.9.0? Well if you read the changelog there is probably a good reason. You can give it a try and report what works and what doesn't. In any case we're not supporting this extremely weird use case. Most people now push for moment >= 2.29.4 due to "security" issues. 2.9.0 was released 7 years ago, you don't get that level of support for paid libraries :)
