### ISSUE TITLE
Missing "AN" ISO Country code for Netherlands Antilles

### ISSUE THREAD

**Issue by visen9** [moment/moment-timezone#937]
### Moment-timezone version which you use:

Version: "moment-timezone": "^0.5.31",

### Issue description:
Calling moment.tz.zonesForCountry("AN", true) returns null.
This happens because there isn't any "AN" code in the library (see moment.tz.countries()).
Please add the "AN" country code (Netherlands Antilles) to solve the issue :)

**Comment by gilmoreorless** [comment]
The country data comes from the [IANA time zone database](https://www.iana.org/time-zones), which doesn't have the `AN` code listed. The main reason for this is that the Netherlands Antilles hasn't officially existed since 2010 (see [Dissolution of the Netherlands Antilles](https://en.wikipedia.org/wiki/Dissolution_of_the_Netherlands_Antilles)). It was split into several entities, each of which has an entry in Moment Timezone's country data:

* Caribbean Netherlands (code `BQ`).
* Curaçao (code `CW`).
* Sint Maarten (code `SX`).
