### ISSUE TITLE
Date decrease by 1day while formatting dates greater than 2037 for the timezones which have DayLightSaving

### ISSUE THREAD

**Issue by SanthoshYAR** [moment/moment-timezone#945]
0.5.32### Moment-timezone version which you use:

Version:

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
When a date is formatted using moment js and if the year is greater than 2037 and the corresponding timezone has DST, date is formatted 1 day less

**Comment by ichernev** [comment]
Can you please provide exact examples, expected, actual results. Normally moment-timezone releases have DST info up until 2037 (well some have until 23xx but this is a bug : https://github.com/moment/moment-timezone/issues/768).

**Comment by mangeshwalhe** [comment]
Hello,
We are facing this issue. Requirement needs user to add a future date (date of retirement, lease end date), which in many usecases is beyond 1st January 2038. It is registered in GMT format, hence when users from APAC region add a date, it is rendered as previous date.
May I know the timeline planned for fixing this issue?

**Comment by gilmoreorless** [comment]
The last few Moment Timezone releases (since `0.5.37`) have increased the data range well past 2038. Can you try with the latest version and see if you're still having these issues?

**Comment by wiznotwiz** [comment]
That's good to know - we will look into upgrading Moment when we update packages this year! I'll report back here if we still have any trouble past 2038 after upgrading.

For anyone still on an older version, I ended up using JS's `.getDate()` and `.getMonth()` functions to accomplish my goal past the year 2038.

**Comment by gilmoreorless** [comment]
I'm going to close this as it looks like the data issue has been resolved.

As a side note, we're looking at a future compromise between data accuracy and file size. At some point we'll likely lock the maximum date range in the data to `<year of release> + 100` (e.g. 2123 for any release built this year).
See https://github.com/moment/moment-timezone/issues/1039 for details. Since you've been directly affected by data range issues, let me know if that would cause a problem.
