### ISSUE TITLE
Moment Time Value with Timezone comes different for two dates

### ISSUE THREAD

**Issue by yasirunilan** [moment/moment-timezone#946]
### Moment-timezone version which you use:

Version:0.5.33

_Note: many issues are resolved if you just upgrade to the latest version_

### Issue description:
I'm using the moment timezone package for date and time handling in my react native mobile app. There I encountered an issue like the following when I passed two date values to moment() function.

Scenario : 
```
let date1 = '1985-08-17';
let date2 = '2021-08-17'
console.log(moment(date1)) // output  -> "1985-08-17T05:00:00.000Z"
console.log(moment(date2)) // output  -> "2021-01-17T06:00:00.000Z"
```

My timezone is America/Mexico_city (GMT -05:00)

**Comment by gilmoreorless** [comment]
Mexico didn't start regular daylight saving rules until 1996, so in 1985 Mexico City was `UTC-06:00` all year round. But from 1996 until now, August 17 has been during the daylight saving period, at `UTC-05:00`. So I'd expect the two dates to have different offsets.

Calling just `moment(dateString)` uses the date settings of the local environment, rather than the data bundled with Moment Timezone. What's confusing me is that the offsets should be the other way around. When I run your example (using `TZ=America/Mexico_City node`) I get the offsets as they should be (note the `06` and `05` in the result):
```
1985-08-17T06:00:00.000Z
2021-08-17T05:00:00.000Z
```
