### ISSUE TITLE
Wrong timezone offset after parsing a string date

### ISSUE THREAD

**Issue by florinrelea** [moment/moment-timezone#960]
### Version
0.5.33

### Issue description:
Wrong utcOffset

### Replication 
https://codepen.io/florinrelea/pen/WNEzaJx

**Comment by gilmoreorless** [comment]
It's a bit difficult to debug this problem with such little information. From the provided link, it looks like you're expecting the UTC offset of `America/Los_Angeles` at `2021-11-05T15:39:42.774Z` to match the UTC offset of the current date/time. Los Angeles [finished daylight saving time](https://www.timeanddate.com/time/change/usa/los-angeles?year=2021) shortly after that timestamp, so the offset would have changed. But I'm not entirely sure if that's what you were expecting, since the linked example may or may not work depending on when it's viewed.

**Comment by florinrelea** [comment]
Hello Gilmore! Thanks for your response. You're right, the problem was that US changed the time on 7th November, so the UTC Offset is actually correct. My bad.
